### ISSUE TITLE
svc pre-trained model

### ISSUE THREAD

**Issue by yanyanxixi** [open-mmlab/Amphion#10]

**Comment by yanyanxixi** [comment]
你好
   请问svc部分声学预训练模型可以开放吗？

**Comment by RMSnow** [comment]
Thanks for your attention! You can try this one: https://huggingface.co/amphion/singing_voice_conversion. You are welcome to try and give us any feedback.

**Comment by yanyanxixi** [comment]
> Thanks for your attention! You can try this one: https://huggingface.co/amphion/singing_voice_conversion. You are welcome to try and give us any feedback.

ok  thank you very much!  it can inference right now
