### ISSUE TITLE
[Help]: about VALLE training

### ISSUE THREAD

**Issue by walker-hyf** [open-mmlab/Amphion#109]
After training valle on libritts, we noticed a drop in the Train Loss and a slight increase in the Valid Loss. Plus, when we trained AR and NAR models for 20 Epochs each, the synthesized speech quality wasn't great, and unfortunately, even after 100 Epochs of team training, the results were disappointing. Did the team encounter an increase in ValidLoss during the training process? I only made use of lexicon without making any other changes.

TensorBoard:
![image](https://github.com/open-mmlab/Amphion/assets/39916348/f58e092a-b0c6-452d-83bd-f1016daf79a8)

INFO:
![image](https://github.com/open-mmlab/Amphion/assets/39916348/df6cc545-f954-4b62-adc3-05e5eae1b84b)

ckpts.json
![image](https://github.com/open-mmlab/Amphion/assets/39916348/3b9fb020-01d0-4466-9572-ae1ad8abdd10)

**Comment by lmxue** [comment]
could you please give some your samples?

**Comment by HarryHe11** [comment]
Hi @walker-hyf , Could you give us some of your samples to help us identify your problems?
