### ISSUE TITLE
System(s) to which the project applies?windows10?Linux？

### ISSUE THREAD

**Issue by liuyuhualilith** [open-mmlab/Amphion#11]
Is this project available for Windows 10? Some of the packages seem to be Linux only?I'm currently running it on Win10, and I'm getting some errors, so I'm not sure if it's an incompatible environment or not.

**Comment by RMSnow** [comment]
We recommend to use Linux-based enviroment to run Amphion. I'm not sure about running it in Windows 10. Maybe some package dependencies can not be installed well. Could you provide more bug details?

**Comment by liuyuhualilith** [comment]
> 我们建议使用基于Linux的环境来运行Amphion。我不确定在Windows 10中运行它。也许某些包依赖项无法很好地安装。您能否提供更多错误详细信息？

**Comment by liuyuhualilith** [comment]
> We recommend to use Linux-based enviroment to run Amphion. I'm not sure about running it in Windows 10. Maybe some package dependencies can not be installed well. Could you provide more bug details?

Ok thank you , I understand, quite a lot of questions came up. I'm now going to try this project with ubuntu.
