### ISSUE TITLE
When will there be preprocessing of Chinese data sets?[Help]: 

### ISSUE THREAD

**Issue by JoyceMind** [open-mmlab/Amphion#112]
When will there be preprocessing of Chinese data sets?

**Comment by ArkhamImp** [comment]
May I ask which task you mentioned?

**Comment by JoyceMind** [comment]
> May I ask which task you mentioned?





uh，TTS of Chinese Language or bilingual--Chinese and English

**Comment by lmxue** [comment]
Amphion is currently supoorting multilingual dataset processing. For more helpful information, please check out #62  and #137 .
