### ISSUE TITLE
[Help]: Format of CustomSVCDataset

### ISSUE THREAD

**Issue by mysxs** [open-mmlab/Amphion#116]
## Problem Overview
I adjusted my data set according to the CustomSVCDataset data set format requirements, but when I executed `sh egs/svc/MultipleContentsSVC/run.sh --stage 1`, I reported an error. The error appeared in this sentence of the metadata.py file: `utterances = sorted(utterances, key=lambda x: x["Duration"])`, the data set must have `Duration`, is there anything else needed to customize the data set?

## Screenshots
(If applicable, add screenshots to help explain your problem.)
![image](https://github.com/open-mmlab/Amphion/assets/88299695/979649ee-6918-4c6c-a0f8-f2d30bfdccf2)
![image](https://github.com/open-mmlab/Amphion/assets/88299695/7851514d-a730-4898-9335-0e89402fad77)

**Comment by mysxs** [comment]
The train.json of my data set is as follows:
![image](https://github.com/open-mmlab/Amphion/assets/88299695/2fb6989f-34c4-469b-a6fe-86b2548b7ac6)

**Comment by RMSnow** [comment]
Hi @mysxs, thanks for your attention!

It seems that your provided `train.json` is not generated by Amphion's code. Our [instruction](https://github.com/open-mmlab/Amphion/tree/main/egs/svc/MultipleContentsSVC#custom-dataset) of CustomSVCDataset means that you can prepare your wavs as the following format:

```
[Your Custom Dataset Path]
 ┣ singer1
 ┃ ┣ song1
 ┃ ┃ ┣ utterance1.wav
 ┃ ┃ ┣ utterance2.wav
 ┃ ┃ ┣ ...
 ┃ ┣ song2
 ┃ ┣ ...
 ┣ singer2
 ┣ ...
```

After that, you need to specify your custom dataset name and its path (`[Your Custom Dataset Path]`) in the `exp_config.json`:

```
    "dataset": [
        "[Exisiting Dataset Name]",
        //...
        "[Your Custom Dataset Name]"
    ],
    "dataset_path": {
        "[Exisiting Dataset Name]": "[Exisiting Dataset Path]",
        //...
        "[Your Custom Dataset Name]": "[Your Custom Dataset Path]"
    },
    "use_custom_dataset": [
        "[Your Custom Dataset Name]"
    ],
```

After that, when you preprocess the custom dataset (`--stage 1`), the Amphion will automatically produce the `train.json` and `test.json` for you (see [this line](https://github.com/open-mmlab/Amphion/blob/eafa50dd57c68c99792349806bb3a186a10bf276/bins/svc/preprocess.py#L108)), where the generated json files will have the `Duration` key.

You can follow the steps above. If there are still any bugs, feel free to let us know.

**Comment by mysxs** [comment]
okok, it turns out that train.json is automatically generated by Amphion. I just found that the directory of my data set is one level higher than CustomSVCDataset. I will modify it and try again~

**Comment by mysxs** [comment]
Hi [RMSnow](https://github.com/RMSnow), thanks for your reply!
okok, it turns out that train.json is automatically generated by Amphion. I just found that the directory of my data set is one level higher than CustomSVCDataset. I will modify it and try again~

**Comment by mysxs** [comment]
Hi [RMSnow](https://github.com/RMSnow), thanks for your attention!
I reorganized my dataset according to the CustomSVCDataset format. I added two pictures to illustrate my dataset, but the previous error was still reported. Amphion did not automatically generate train.json.
the format of my dataset:
![image](https://github.com/open-mmlab/Amphion/assets/88299695/8643a41f-a0af-4b35-ba7e-49481e9abb57)
![image](https://github.com/open-mmlab/Amphion/assets/88299695/324ea12f-c9d6-487f-a638-98fe700ee601)
error:
![image](https://github.com/open-mmlab/Amphion/assets/88299695/b14e3b42-53b7-483a-83aa-4f29f8bb1072)

**Comment by viewfinder-annn** [comment]
Hi @mysxs !

Seeing your provided screenshots, I came up with two possible reasons:
1. You are not specifying `use_custom_dataset` field in your config.json file. You need to add a field like this if you havn't done it:
```json
"dataset_path": [
    "ESD": ...
]
"use_custom_dataset": [
    "ESD"
],
```
2. You are setting the `processed_dir` same as your raw audio dir. It's recommended not to do so. During the preprocess stage a dir with the name of your dataset name will be created in the `processed_dir` path. In this case it will create another `"/egs/ESD"` dir which may cause overide of your original files. You can try to set this field default("data").

**Comment by mysxs** [comment]
Hi @viewfinder-annn,thank you for your response. Following your advice, I corrected my dataset path, and I successfully resolved the issue. Thank you!

**Comment by cckamiya** [comment]
您好我也按照您写的目录格式设置了数据，

![Image](https://github.com/user-attachments/assets/92a671da-c10c-4daa-8295-0c2ebaa79610)

![Image](https://github.com/user-attachments/assets/ac3abdea-5211-4a55-948f-7b225e931be2)
但是我运行sh egs/svc/DiffComoSVC/run.sh --stage 1,报错：

![Image](https://github.com/user-attachments/assets/3a3a610f-ece1-42dd-b62e-31ca04996133)
为什么
