### ISSUE TITLE
Visualization of the generative process

### ISSUE THREAD

**Issue by l1amw** [open-mmlab/Amphion#124]
Hello, great work! I was wondering how to implement the visualization of the generative process mentioned in your paper, thanks.

**Comment by RMSnow** [comment]
Hi @l1amw, thanks for your attention! The amphion visualization part is under developing. We expect to release it in next month!

**Comment by yuantuo666** [comment]
Hi @l1amw, the visualization component has been released now. You may check the details [here](https://github.com/open-mmlab/Amphion/tree/main/egs/visualization).
If you have any further questions about visualization, feel free to re-open this issue. We are glad to follow up!
