### ISSUE TITLE
[Help]: The CustomSVCDataset inference/conversion problem occurred

### ISSUE THREAD

**Issue by mysxs** [open-mmlab/Amphion#128]
## Problem Overview
An error occurred in infer_target_speaker while inferring with own data set

## Steps Taken
When I did the inference/conversion, I was told that the problem corresponding to target_speaker could not be found
![image](https://github.com/open-mmlab/Amphion/assets/88299695/fe4c4636-267e-470e-b05b-d1bc1a3e90fa)
The error appears in infer_target_speaker.
Execute the infer_target_speaker command as follows:` --infer_target_speaker 16 \`
Because my singers.json is like this, I chose `"[ESD]_0017": 16` as my target_speaker, but I don't have a folder for` "[ESD]_0017": 16` under the data path
![微信图片_20240131210212](https://github.com/open-mmlab/Amphion/assets/88299695/628bc7f4-5128-4641-b686-5a5c7f506e15)
![image](https://github.com/open-mmlab/Amphion/assets/88299695/5b941eb4-3395-430e-9239-963eddd74251)
Only `'[ESD]' `(all my  CustomSVCDataset) and `0004_000563` (my source_audio) in the data path
![image](https://github.com/open-mmlab/Amphion/assets/88299695/6f6144be-c897-4126-be6f-d958362b402a)

In `data/[ESD]/mel_min_max_stats`, there are `mel_max.npy` and` mel_min.npy`, and in `data/[ESD]/mels`, there are all the.npy files for my CustomSVCDataset
![image](https://github.com/open-mmlab/Amphion/assets/88299695/9d0551c4-8cce-4dd6-ae7f-7a20720e341f)
So I can't find the infer_target_speaker.npy file

**Comment by Lokshaw-Chau** [comment]
Hi @mysxs !

I think simply run command with `--infer_target_speaker '[ESD]_0017' \` may sovle your problem.

Actually we will look up `[ESD]_0017` in `singer.json` to get `16` which is the index of the target singer's embedding in your trained model.

**Comment by mysxs** [comment]
Hi @Lokshaw-Chau !
Ok, it worked, then a new problem appeared, I continued to solve it, thank you for your reply!
