### ISSUE TITLE
[BUG]: prompt_examples/*.wav missing in NaturalSpeech2

### ISSUE THREAD

**Issue by xiangmy21** [open-mmlab/Amphion#132]
## Describe the bug
when use NaturalSpeech2 inference, it report RuntimeError: not found `NaturalSpeech2/prompt_example/ref_audio.wav`.
same as https://github.com/open-mmlab/Amphion/issues/114, but in NaturalSpeech2, not VALLE. I think the problem comes from the .gitignore as well, it ignores all *.wav expect prompt_examples in VALLE now.

## How To Reproduce
follow https://huggingface.co/amphion/naturalspeech2_libritts . 

## Expected behavior
such as:
```
RuntimeError: Failed to open the input "~/amphion/egs/tts/NaturalSpeech2/prompt_example/ref_audio.wav" (No such file or directory).
```

**Comment by xiangmy21** [comment]
Oh I get it, not a problem. Just download from the demo page https://speechresearch.github.io/naturalspeech2/ or use own voice. But better provide a default example. Thanks~

**Comment by lmxue** [comment]
Thanks for your attention and support towards our work. I will close this issue. If you have any further questions about `prompt_examples`, please feel free to re-open this issue. We are glad to follow up!
