### ISSUE TITLE
[Help]: Soft link not work

### ISSUE THREAD

**Issue by xiangmy21** [open-mmlab/Amphion#133]
## Problem Overview
I follow the https://huggingface.co/amphion/naturalspeech2_libritts and https://github.com/open-mmlab/Amphion/tree/main/egs/tts/NaturalSpeech2 to use NaturalSpeech2 for inference, but the soft link created by command `ln -s  ../../../naturalspeech2_libritts  ckpts/tts/` seems not work.
It still report `FileNotFoundError: [Errno 2] No such file or directory: '~/amphion/ckpts/tts/naturalspeech2_libritts/checkpoint/epoch-0089_step-0512912_loss-6.367693/pytorch_model.bin'`

## Screenshots
<img width="987" alt="image" src="https://github.com/open-mmlab/Amphion/assets/90919434/c7f8fdb9-53ba-4047-9b9b-9e6e1bf72e0e">
I'm sure `/home/srt15/naturalspeech2/checkpoint/epoch-0089_step-0512912_loss-6.367693/pytorch_model.bin` is existent.

**Comment by HarryHe11** [comment]
Could you please share the details of the files located in the '~/amphion/ckpts/tts/naturalspeech2_libritts/checkpoint/epoch-0089_step-0512912_loss-6.367693' folder?

**Comment by xiangmy21** [comment]
There is only a soft link in `/home/srt15/amphion/ckpts/tts/`，as the first capture shows.
now I deleted the soft link, and move the `/home/srt15/naturalspeech2_libritts/` folder directly into `/home/srt15/amphion/ckpts/tts/naturalspeech2_libritts/`，and it works. So I wonder why the soft link doesn't work.
<img width="258" alt="image" src="https://github.com/open-mmlab/Amphion/assets/90919434/c961e946-d946-4e1e-be19-d02c25bf157c">

**Comment by HarryHe11** [comment]
In this situation, it seems to be related to the way Accelerate handles model loading. To potentially address this issue, you might consider introducing a piece of code before the model loading process. This additional step involves obtaining the actual path of the symlinked file. Here's a revised version of the code snippet:
```
# Resolve the actual path of the symlinked file
real_ckpt_path = os.path.realpath([YOUR_SOFT_LINK_PATH])
# Load the model using the resolved path
load_model(real_ckpt_path)
```

**Comment by xiangmy21** [comment]
Oh, God! Sorry, it's my problem. I add the soft link again and it works:
<img width="591" alt="image" src="https://github.com/open-mmlab/Amphion/assets/90919434/3f578dd8-794d-4201-bbe2-c10dacad5c49">
When using relative path to add soft link, the path should be based on the link path. Maybe I used the wrong relative path at first.
Sorry for disturbing, and thanks for your help!
