### ISSUE TITLE
[Help]: Inference

### ISSUE THREAD

**Issue by mysxs** [open-mmlab/Amphion#142]
## Problem Overview
In `Amphion/bins/svc/inference.py`, acoustics_dir is not assigned a value and is set to None. Is this correct? Because while debugging inference.py, I found that due to acoustics_dir being None, an error occurs at line 192 in `Amphion/models/svc/base/svc_dataset.py: ``spk2id_path = os.path.join(args.acoustics_dir, cfg.preprocess.spk2id)`. The error message is `TypeError: expected str, bytes, or os.PathLike object, not NoneType.`

## Steps Taken
`Amphion/bins/svc/inference.py:`
```
   parser.add_argument(
        "--acoustics_dir",
        type=str,
        help="Acoustics model checkpoint directory. If a directory is given, "
        "search for the latest checkpoint dir in the directory. If a specific "
        "checkpoint dir is given, directly load the checkpoint.",

)
```

## Screenshots
![image](https://github.com/open-mmlab/Amphion/assets/88299695/56be06dd-c16b-4105-8a28-e12069a6ede3)

**Comment by RMSnow** [comment]
Hi @mysxs, did you specify the `--infer_expt_dir` when inference? You can refer to [this part](https://github.com/open-mmlab/Amphion/tree/main/egs/svc/MultipleContentsSVC#run-1) as the instruction.

**Comment by mysxs** [comment]
Hi @RMSnow ,thank your apply,OK I fixed this issue and a new problem appeared: when I run the inference, an error is reported, and it is written in `Amphion/models/base/new_inference.py` that it says `ckpt_list = [ckpt for ckpt in Path(vocoder_dir).glob("*.pt")]` that need a .pt file, but I use Hifi-Gan, It doesn't have a .pt file, there are many .bin files, which .bin file should I specify?

**Comment by Adorable-Qin** [comment]
Hi @mysxs !

You may refer to issue [105](https://github.com/open-mmlab/Amphion/issues/105) for the checkpoint loading problem.

We are going to provide an official update to solve this issue later. Before that, you could use our pretrained BigVGAN vocoder if you don't want to implement your inference code.

You may find quick reference guides from our hugging face pages [svc](https://huggingface.co/amphion/singing_voice_conversion) and [vocoder](https://huggingface.co/amphion/BigVGAN_singing_bigdata).

If you have any other problem, feel free to contact us!

**Comment by mysxs** [comment]
Hi [Adorable-Qin](https://github.com/Adorable-Qin)~ I have resolved the issue. Thank you for your response.

**Comment by Adorable-Qin** [comment]
Glad to hear that!

We will close this issue. Feel free to re-open it once you have other questions!
