### ISSUE TITLE
[Help]: What configuration of server is appropriate to run this project.

### ISSUE THREAD

**Issue by liuyuhualilith** [open-mmlab/Amphion#146]
What configuration of server is appropriate to run this project.

I want to try to rent a server to run this project on AliCloud platform, but I am not sure what configuration of server is suitable, can you provide some suggestions?
Here's some of the info I checked off, (I'm mostly more interested in valle training)
Very much looking forward to your answers to my questions, thanks!

![image](https://github.com/open-mmlab/Amphion/assets/142777788/a21e89d0-4159-481a-8a6a-cb67a665337c)
![image](https://github.com/open-mmlab/Amphion/assets/142777788/8b282fa3-5289-4115-bbbe-00701f24cde4)

**Comment by lmxue** [comment]
To determine the appropriate server configuration for running your project, especially focusing on VALLE training, several factors need consideration: 
* GPU: Consider renting instances with GPUs. On AliCloud, you might look into their GPU-accelerated instances like NVIDIA Tesla or AMD GPUs.
* CPU: Powerful CPUs is also important for tasks like data preprocessing.  Look for instances with high-performance CPUs.
* Memory (RAM): A minimum of 16GB RAM is often recommended, but depending on your dataset size, you might need more.
* Storage: Consider the amount of storage required for your dataset, model checkpoints, and any other data. SSD storage is preferred for faster data access.

For more specific recommendations, you might want to consider consulting with a cloud service provider like AliCloud. They often provide pre-configured instances optimized for deep learning tasks, which can simplify the process of selecting the right configuration for your project. Additionally, they may offer guidance or support services to help optimize your setup for performance and cost-effectiveness.

**Comment by lmxue** [comment]
Hi @liuyuhualilith , if you have any further questions about the configuration of the server, please feel free to re-open this issue. We are glad to follow up!
