### ISSUE TITLE
Error running "sh env.sh"

### ISSUE THREAD

**Issue by liuyuhualilith** [open-mmlab/Amphion#15]
It's very hard, I get a lot of errors when I run "sh env.sh"
![1](https://github.com/open-mmlab/Amphion/assets/142777788/ad91b259-419d-445e-8b3a-93759be8adfd)
![2](https://github.com/open-mmlab/Amphion/assets/142777788/6449d6e4-8bbf-491e-8ad8-c88f9324d666)

**Comment by RMSnow** [comment]
It looks like a `NetConnnectionError` of your server. Can you try another pip mirror source?
