### ISSUE TITLE
[Feature]: FACodec training

### ISSUE THREAD

**Issue by TechInterMezzo** [open-mmlab/Amphion#156]
Will you release the source code for the FACodec training pipeline?

**Comment by HeCheng0625** [comment]
Hi, thank you very much for your attention, we are still developing the training code.

**Comment by huutuongtu** [comment]
> Hi, thank you very much for your attention, we are still developing the training code.

@HeCheng0625 Do you plan to release another FACodec checkpoint that supports different hop size, such as 320, which is commonly used in other SSL pre-trained models?

**Comment by jiaqili3** [comment]
Hi @TechInterMezzo , we're releasing the FACodec training code in Amphion (it's now in a PR #229  and will be merged soon). You're welcome to check it out. Thanks!
