### ISSUE TITLE
[Help]: May I ask when naturalspeech3_facodec/resolve/main/ns3_facodec_encoder_v2.bin will be released?

### ISSUE THREAD

**Issue by wcr369** [open-mmlab/Amphion#157]
I didn't see naturalspeech3_facodec/resolve/main/ns3_facodec_encoder_v2.bin in https://huggingface.co/amphion/naturalspeech3_facodec/tree/main, and I want to do some zero-shot voice conversions using FACodec.

**Comment by HeCheng0625** [comment]
Hi, we have release it now.
