### ISSUE TITLE
[BUG]: Typos in TTA task

### ISSUE THREAD

**Issue by fpicetti** [open-mmlab/Amphion#158]
Spotted the following typos, can you please correct `vaild` to `valid`?

https://github.com/open-mmlab/Amphion/blob/58dc8707dec735fdb381d351fc123bec9242b204/egs/tta/autoencoderkl/exp_config_base.json#L9

https://github.com/open-mmlab/Amphion/blob/58dc8707dec735fdb381d351fc123bec9242b204/egs/tta/audioldm/exp_config_base.json#L9

**Comment by HeCheng0625** [comment]
Sure! We will fix it.

**Comment by fpicetti** [comment]
Thank you, closing this.
