### ISSUE TITLE
[Help]: while trainning transfomerSVC

### ISSUE THREAD

**Issue by suted2** [open-mmlab/Amphion#164]
## Problem Overview
(Briefly and clearly describe the issue you're facing and seeking help with.)

Hello, While I train transformerSVC, 

``` This error come out 
TypeError: WhisperExtractor.extract_content_features() takes 2 positional arguments but 3 were given

```

## Steps Taken
(Detail your attempts to resolve the issue, including any relevant steps or processes.)
I add 

## Expected Outcome
(A clear and concise description of what you expected to happen.)

## Screenshots
(If applicable, add screenshots to help explain your problem.)
![image](https://github.com/open-mmlab/Amphion/assets/101646531/dbd1eac2-a079-4645-914f-cdeed4981475)

## Environment Information

- I am using Colab PRO 

## Additional context
(Add any other context about the problem here.)

**Comment by suted2** [comment]
Oh, It works when i copy and paste at colab cell, 
-> it works when i change args -> wavs , lens  to wavs. 
but even i change content_extractor.py 
it still doesn't work when i use run.sh


![image](https://github.com/open-mmlab/Amphion/assets/101646531/a1ae9d8d-641d-416f-8682-a8b4759e42e6)

**Comment by RMSnow** [comment]
Hi @suted2 , sorry for that! I have patched for it. Would you mind trying [this branch](https://github.com/RMSnow/Amphion/tree/patch_for_content_extractor) of PR https://github.com/open-mmlab/Amphion/pull/165?

**Comment by suted2** [comment]
Okay! thx!!!

**Comment by RMSnow** [comment]
Hi @suted2, if you have any further questions about transformerSVC, feel free to re-open this issue. We are glad to follow up!
