### ISSUE TITLE
[BUG]: FastSpeech2 train failed when under cuda_devices="1,2,3"

### ISSUE THREAD

**Issue by huangxu1991** [open-mmlab/Amphion#167]
Errors as follows:

torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 

Failures:
[1]:
  time      : 2024-03-27_14:52:55
  host      : iv-ycucodpkaowuxjsftsvp
  rank      : 1 (local_rank: 1)
  exitcode  : -11 (pid: 45620)
  error_file: <N/A>
  traceback : Signal 11 (SIGSEGV) received by PID 45620
[2]:
  time      : 2024-03-27_14:52:55
  host      : iv-ycucodpkaowuxjsftsvp
  rank      : 2 (local_rank: 2)
  exitcode  : -11 (pid: 45621)
  error_file: <N/A>
  traceback : Signal 11 (SIGSEGV) received by PID 45621

Root Cause (first observed failure):
[0]:
  time      : 2024-03-27_14:52:55
  host      : iv-ycucodpkaowuxjsftsvp
  rank      : 0 (local_rank: 0)
  exitcode  : -11 (pid: 45619)
  error_file: <N/A>
  traceback : Signal 11 (SIGSEGV) received by PID 45619

However, it's fine when use only one gpu!

**Comment by RMSnow** [comment]
Hi @huangxu1991, if you have any further questions, feel free to re-open this issue. We are glad to follow up!

**Comment by huangxu1991** [comment]
ok
