### ISSUE TITLE
[Feature]: For Music - VALL-E transformer RAG (and other embedding solutions)

### ISSUE THREAD

**Issue by bennmann** [open-mmlab/Amphion#170]
## Is your feature request related to a problem? Please describe.
The problem is I want more of the specific kind of music I already own.

## Describe the solution you'd like
It would be good for the kwargs to include user owned music, which can be embedded (like RAG for LLM transformer) into a Text prompt. "Using the music provided, please generate a song in the style of $$RAG_EMBEDDING_HERE"

## Describe alternatives you've considered
There are no alternatives like this for music yet.

## Additional context
HuggingFace sentence-transformers page for LLM equivalent: https://huggingface.co/sentence-transformers

**Comment by RMSnow** [comment]
Hi @bennmann, it seems like you are looking for a Text-to-Music function? We have been devoting to developing this task. Hope we can release in this year. Before that, you are welcome to try our TTA model!
