### ISSUE TITLE
[Help]: Latent

### ISSUE THREAD

**Issue by a897456** [open-mmlab/Amphion#174]
https://github.com/open-mmlab/Amphion/blob/5cb75d8d605ef12c90c64ba2e04919f4d5d834a1/models/tts/naturalspeech2/ns2.py#L57
Now, when we look for latent, is the decoder and quantizer in the reverse order?

**Comment by HeCheng0625** [comment]
Hi, NS2 paper uses latent after RVQ (in fact, it is the continuous vector corresponding to discrete codes), you can check the details in NS2 paper.

**Comment by a897456** [comment]
> Hi, NS2 paper uses latent after RVQ (in fact, it is the continuous vector corresponding to discrete codes), you can check the details in NS2 paper.

I understand. I always thought that wav becomes latent after encoder, but in fact, it becomes latent after encoder and RVQ, right?

**Comment by HarryHe11** [comment]
> > Hi, NS2 paper uses latent after RVQ (in fact, it is the continuous vector corresponding to discrete codes), you can check the details in NS2 paper.
> 
> I understand. I always thought that wav becomes latent after encoder, but in fact, it becomes latent after encoder and RVQ, right?

yes, NS2 paper uses the latent after RVQ, For details, please refer to https://arxiv.org/abs/2304.09116.
