### ISSUE TITLE
[Help]: Some questions about the SVC model

### ISSUE THREAD

**Issue by Yuki-zik** [open-mmlab/Amphion#187]
## Problem Overview
I have two problems when using your model:
1. Why is the como model larger than the teacher model in diffcomoSVC?
2. If there are multiple singers in my data set, will the data of singer A improve the quality of singer B’s timbre conversion?

**Comment by Lokshaw-Chau** [comment]
Hi, @Yuki-zik. 
1. Actually a saved diffcomoSVC checkpoint contains a target model (EMA updated) and a student model (online updated). They are both the same architecture with the teacher model. We design in this manner for resume which requires the both to smoothly recover the latest training status. During inference, only the target model is activated.
2. It's hard to give a determinated conclusion. But in my experience, a large multiple singers dataset often lead to a better conversion result for each singer. If you are only targeted at one singer, it's always better to collect as much target singer data as possible. If you can't collect enough data, a possible solution is to pre-train a model on multiple singers dataset and then finetune the pre-trained model on your target singer dataset.

**Comment by Yuki-zik** [comment]
> 1. Actually a saved diffcomoSVC checkpoint contains a target model (EMA updated) and a student model (online updated). They are both the same architecture with the teacher model. We design in this manner for resume which requires the both to smoothly recover the latest training status. During inference, only the target model is activated.
> 2. It's hard to give a determinated conclusion. But in my experience, a large multiple singers dataset often lead to a better conversion result for each singer. If you only target at one singer, it's always better to collect as much target singer data as possible. If you can't collect enough data, a possible solution is to pre-train a model on multiple singers dataset and then finetune the pre-trained model on your target singer dataset.

I understand, thank you for your answer.
