### ISSUE TITLE
[Help]: Infer AR solely for VALL-E?

### ISSUE THREAD

**Issue by caigun** [open-mmlab/Amphion#191]
## Problem Overview
I modified the VALL-E model and trained on AR, then NAR; after when I encountered some issues with the AR part, where the length of the result cannot be ensured, so I want to infer the AR ckpt since there is no need for further training on NAR.

## Expected Outcome
Run the infer step with only AR ckpt, and output the AR layer result (shape or values)

**Comment by lmxue** [comment]
Hi @caigun ,  we can provide the AR checkpoint for your convenience. After uploading the AR checkpoint to Hugging Face, I will post the link here.
