### ISSUE TITLE
[Help]: NaturalSpeech2 training and data preprocess issue

### ISSUE THREAD

**Issue by CreepJoye** [open-mmlab/Amphion#206]
Hello,I would like to run `sh egs/tts/NaturalSpeech2/run_train.sh`,and it reports :
`usage: accelerate <command> [<args>]`
```Accelerate CLI tool: error: argument {config,estimate-memory,env,launch,tpu-config,test}: invalid choice: /home/lqb/project/Amphion/bins/tts/train.py' (choose from 'config', 'estimate-memory', 'env', 'launch', 'tpu-config', 'test')```
How should I handle this issue?
thank you for your patient explanation!

**Comment by CreepJoye** [comment]
1. When I follow other Amphion TTS recipes for the data processing,it seems works but not totally.I get these files in egs/tts/NaturalSpeech2/data_processed/libritts,but no content features.
![image](https://github.com/open-mmlab/Amphion/assets/135318695/d432af58-dcdc-4964-853f-ffbd32fc8bef)
![image](https://github.com/open-mmlab/Amphion/assets/135318695/8e05b2b1-776d-40f1-ab82-8c9a01d59556)
2. How should I set the path of the "metadata_dir" in NaturalSpeech2/exp_config.json/"preprocess"?I don't know what is "metadata"  and it seems like I get no "metadata" since I have created a 'metadata' folder and set the path of 'metadata' to this folder, but it is empty.

Your responses are greatly appreciated！！！

**Comment by chazo1994** [comment]
I face same issues!

**Comment by CreepJoye** [comment]
> I face same issues! Change "accelerate" to "accelerate launch" in run_train.sh

Thank you,I have solved the problem already

**Comment by Linghuxc** [comment]
> launch
Hello, How did you solve this problem? I made the same mistake:```
 usage: accelerate <command> [<args>]
Accelerate CLI tool: error: argument {config,estimate-memory,env,launch,tpu-config,test}: invalid choice: /home/Amphion/bins/tts/train.py' (choose from 'config', 'estimate-memory', 'env', 'launch', 'tpu-config', 'test')
```
I then encountered this error after changing "accelerate" in run_train.sh to "accelerate launch": `usage: train.py [-h] --config CONFIG --exp_name EXP_NAME [--resume] [--log_level LOG_LEVEL] [--resume_type RESUME_TYPE] [--checkpoint_path CHECKPOINT_PATH] [--train_stage TRAIN_STAGE] [--ar_model_ckpt_dir AR_MODEL_CKPT_DIR]
train.py: error: unrecognized arguments: \
Traceback (most recent call last):
  File "/home/anaconda3/envs/amphion/bin/accelerate", line 8, in <module>
    sys.exit(main())
  File "/home/anaconda3/envs/amphion/lib/python3.9/site-packages/accelerate/commands/accelerate_cli.py", line 47, in main
    args.func(args)
  File "/home/anaconda3/envs/amphion/lib/python3.9/site-packages/accelerate/commands/launch.py", line 994, in launch_command
    simple_launcher(args)
  File "/home/anaconda3/envs/amphion/lib/python3.9/site-packages/accelerate/commands/launch.py", line 636, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
subprocess.CalledProcessError: Command '['/home/anaconda3/envs/amphion/bin/python3.9', '/home/Amphion/bins/tts/train.py', '--config=/home/Amphion/egs/tts/NaturalSpeech2/exp_config.json', '--exp_name=ns2_libritts', '--log_level', 'debug', '\\']' returned non-zero exit status 2.`
