### ISSUE TITLE
[BUG]: could u pls help me with this? thanks!

### ISSUE THREAD

**Issue by A-d-DASARE** [open-mmlab/Amphion#214]
DEPRECATION: omegaconf 2.0.6 has a non-standard dependency specifier PyYAML>=5.1.*. pip 24.1 will enforce this behaviour change. A possible replacement is to upgrade to a newer version of omegaconf or contact the author to suggest that they release a version with a conforming dependency specifiers. Discussion can be found at https://github.com/pypa/pip/issues/12063

**Comment by jiaqili3** [comment]
Hi, could you provide more detailed information, like what command you used to see this, and your OS version? Thanks. 
BTW, we recommend installing via conda, 

```bash
# Install Python Environment
conda create --name amphion python=3.9.15
conda activate amphion

# Install Python Packages Dependencies
sh env.sh
```

**Comment by jiaqili3** [comment]
> v.sh, I am getting that warning. and final remarks as below
> 
> "DEPRECATION: omegaconf 2.0.6 has a non-standard dependency specifier PyYAML>=5.1.*. pip 24.1 will enforce this behaviour change. A possible replacement is to upgrade to a newer version of omegaconf or contact the author to suggest that they release a version with a conforming dependency specifiers. Discussion can be

Yeah, I think this is fine

**Comment by jiaqili3** [comment]
- Hi @A-d-DASARE if you have any further questions about installation, feel free to re-open this issue. We are glad to follow up!
