### ISSUE TITLE
doesnt support python 

### ISSUE THREAD

**Issue by xalteropsx** [open-mmlab/Amphion#218]
File "Z:\software\python11\Lib\site-packages\omegaconf\omegaconf.py", line 857, in _create_impl
    raise ValidationError(
omegaconf.errors.ValidationError: Object of unsupported type: '_MISSING_TYPE'
    full_key:
    object_type=None

**Comment by jiaqili3** [comment]
Hi, we recommend using conda for installation, we recommend following the installation guidance on README.md. Conda could be installed in https://conda.io/docs/user-guide/install/
```bash
# Install Python Environment
conda create --name amphion python=3.9.15
conda activate amphion

# Install Python Packages Dependencies
sh env.sh
```
