### ISSUE TITLE
Questions about Training, Models, and Plan for Chinese TTS

### ISSUE THREAD

**Issue by LIUKAI0815** [open-mmlab/Amphion#221]
Could the current TTS support Chinese datasets?

**Comment by jiaqili3** [comment]
Hi, our TTS models currently support English datasets, Chinese dataset support is currently in development for valle. For valle it only needs changing g2p to Chinese g2p like pypinyin, phonemizer. Alhough the public release of such a Chinese model is still in future plan.

**Comment by LIUKAI0815** [comment]
Thank you for your answer
