### ISSUE TITLE
[Help]: how to output 48k hz sample rate audio in svc

### ISSUE THREAD

**Issue by ILG2021** [open-mmlab/Amphion#230]
The default output is very low quality, only 24k hz, can not be used in production. Is there anyway to improve this?

**Comment by ILG2021** [comment]
Anyone can gives help, I am using MultipleContentsSVC.

**Comment by ILG2021** [comment]
Thank you for your reply. I change the configs like:
1. egs/svc/MultipleContentsSVC/exp_config.json, change sample_rate to 48000 in "preprocess" field.
2. pretrained/bigvgan/args.json, change sample_rate to 48000 in "preprocess" field. I am using Amphion Singing BigVGAN

am I right? should I change other things?

**Comment by Adorable-Qin** [comment]
> Thank you for your reply. I change the configs like:
> 
> 1. egs/svc/MultipleContentsSVC/exp_config.json, change sample_rate to 48000 in "preprocess" field.
> 2. pretrained/bigvgan/args.json, change sample_rate to 48000 in "preprocess" field. I am using Amphion Singing BigVGAN
> 
> am I right? should I change other things?

Please note that the pretrained BigVGAN provided is trained under a 24k sampling rate. As a result, it cannot be used directly by changing the `sample_rate` in the `args.json`. Please be advised that you will need to locate an alternative available checkpoint from the Internet or train your vocoder using 48k data.

**Comment by ILG2021** [comment]
Ok, I will try. Another problem, Amphion svc needs preprocess data to inference. Can it improve?

**Comment by Adorable-Qin** [comment]
> Ok, I will try. Another problem, Amphion svc needs preprocess data to inference. Can it be improved?

Yes, we are currently developing an online extraction version, which will be made available in the near future.

**Comment by ILG2021** [comment]
How could I use the nsfhifigan vocoder?
https://github.com/openvpi/vocoders/releases
If I create a folder, put the checkpoint file and move egs/vocoder/gan/nsfhifigan/exp_config.json to the folder and rename it to args.json, will it work?
