### ISSUE TITLE
[Docs]: 

### ISSUE THREAD

**Issue by dukGuo** [open-mmlab/Amphion#238]
Hi , First of all, thanks for your work on building this dataset and open-source the pipeline, very impressive.

## Documentation Reference
https://github.com/open-mmlab/Amphion/blob/main/preprocessors/Emilia/README.md#acknowledgement-
<img width="621" alt="image" src="https://github.com/open-mmlab/Amphion/assets/61131508/17443197-34ad-40a0-97bf-24ae882b07a5">

## Feedback on documentation
The Speaker Diarization toolkit is different from the paper. 
![image](https://github.com/open-mmlab/Amphion/assets/61131508/d0bed93d-6cfc-4853-b7c4-645f4c276722)

**Comment by yuantuo666** [comment]
@dukGuo  Thank you for reporting this issue, we have fixed the typo here: https://github.com/open-mmlab/Amphion/pull/237
