### ISSUE TITLE
Phoneme extraction very slow

### ISSUE THREAD

**Issue by treya-lin** [open-mmlab/Amphion#24]
Hi I am new to Amphion and am just starting to try the VITS recipe.

I am doing the preprocessing stage by simply running: 
```
bash egs/tts/VITS/run.sh --stage 1
```
However, it seems the operation is very slow considering LJSpeech is actually not a very big dataset with only 13k audios. The weirdest part is the phoneme extraction part, on my server it is as slow as this:
```
Extracting content features for LJSpeech...
Extracting phoneme sequence for LJSpeech...
 30%|█████████████████▋                                        | 3987/13100 [49:53<2:03:53,  1.23it/s]
```
I checked the codes and it seems it is not doing something very complicated, just getting the phonemes from either lexicon or g2p_en and then save it as an independent phoneme file, so I wonder if this speed is normal, how does it operate in your local environment? If it is also very slow at your end, I wonder if you guys would consider making it work concurrently?

[phone_extractor.py](https://github.com/open-mmlab/Amphion/blob/c113ec3d242872f486615ada30f7fd76a7dc9180/processors/phone_extractor.py#L115C1-L123C43)
```
    for utt in tqdm(metadata):
        uid = utt["Uid"]
        text = utt["Text"]


        phone_seq = phone_extractor.extract_phone(text)


        phone_path = os.path.join(out_path, uid + ".phone")
        with open(phone_path, "w") as fin:
            fin.write(" ".join(phone_seq))
```
[g2p_module.py](https://github.com/open-mmlab/Amphion/blob/c113ec3d242872f486615ada30f7fd76a7dc9180/text/g2p_module.py#L205C1-L221C22)
```
    def preprocess_english(self, text):
        text = text.rstrip(punctuation)


        g2p = G2p()
        phones = []
        words = re.split(r"([,;.\-\?\!\s+])", text)
        for w in words:
            if w.lower() in self.lexicon:
                phones += self.lexicon[w.lower()]
            else:
                phones += list(filter(lambda p: p != " ", g2p(w)))
        phones = "}{".join(phones)
        phones = re.sub(r"\{[^\w\s]?\}", "{sp}", phones)
        phones = phones.replace("}{", " ")
        
        
        return phones
```

**Comment by lmxue** [comment]
What’s the machine did you run on? It takes only about several minutes to extract phoneme features of all 12,445 utterances when I tested on NVidia GeForce RTX 3090.

**Comment by RMSnow** [comment]
> Hi I am new to Amphion and am just starting to try the VITS recipe.
> 
> I am doing the preprocessing stage by simply running:
> 
> ```
> bash egs/tts/VITS/run.sh --stage 1
> ```
> 
> However, it seems the operation is very slow considering LJSpeech is actually not a very big dataset with only 13k audios. The weirdest part is the phoneme extraction part, on my server it is as slow as this:
> 
> ```
> Extracting content features for LJSpeech...
> Extracting phoneme sequence for LJSpeech...
>  30%|█████████████████▋                                        | 3987/13100 [49:53<2:03:53,  1.23it/s]
> ```
> 
> I checked the codes and it seems it is not doing something very complicated, just getting the phonemes from either lexicon or g2p_en and then save it as an independent phoneme file, so I wonder if this speed is normal, how does it operate in your local environment? If it is also very slow at your end, I wonder if you guys would consider making it work concurrently?
> 
> [phone_extractor.py](https://github.com/open-mmlab/Amphion/blob/c113ec3d242872f486615ada30f7fd76a7dc9180/processors/phone_extractor.py#L115C1-L123C43)
> 
> ```
>     for utt in tqdm(metadata):
>         uid = utt["Uid"]
>         text = utt["Text"]
> 
> 
>         phone_seq = phone_extractor.extract_phone(text)
> 
> 
>         phone_path = os.path.join(out_path, uid + ".phone")
>         with open(phone_path, "w") as fin:
>             fin.write(" ".join(phone_seq))
> ```
> 
> [g2p_module.py](https://github.com/open-mmlab/Amphion/blob/c113ec3d242872f486615ada30f7fd76a7dc9180/text/g2p_module.py#L205C1-L221C22)
> 
> ```
>     def preprocess_english(self, text):
>         text = text.rstrip(punctuation)
> 
> 
>         g2p = G2p()
>         phones = []
>         words = re.split(r"([,;.\-\?\!\s+])", text)
>         for w in words:
>             if w.lower() in self.lexicon:
>                 phones += self.lexicon[w.lower()]
>             else:
>                 phones += list(filter(lambda p: p != " ", g2p(w)))
>         phones = "}{".join(phones)
>         phones = re.sub(r"\{[^\w\s]?\}", "{sp}", phones)
>         phones = phones.replace("}{", " ")
>         
>         
>         return phones
> ```

Hi, thanks for your feedback! Could you provide more details about your machine (such as CPU or I/O performance)?

**Comment by treya-lin** [comment]
> Hi, thanks for your feedback! Could you provide more details about your machine (such as CPU or I/O performance)?

Hi the server has 48 cpu processors and each processor has 12 cores. Should be an appropriate setup? May I know how to check I/O performance?

```
$ cat /proc/cpuinfo |grep "processor"|wc -l
48
$ cat /proc/cpuinfo |grep "cores"|sort -u
cpu cores       : 12
```

**Comment by treya-lin** [comment]
> It may depend on the io speed of your machine. I tested it on my machine. And it took several minutes to extract phoneme features of all 12,445 utterances in LJSpeech.

Could you share the whole console output of your preprocessing precedure? I tried cleaning my cache and disk but it is still the same. Here is my console output:
```
$ bash egs/tts/VITS/run.sh
 --stage 1
Exprimental Configuration File: /newdisk2T/yanfazu/tts_space/Amphion/egs/tts/VITS/exp_config.json
Preprocess LJSpeech...
----------
Dataset splits for LJSpeech...

13100it [00:00, 432337.83it/s]
100%|██████████████████████████████████████████████| 12445/12445 [03:19<00:00, 62.37it/s]
Train_hours= 22.76966582262538
100%|██████████████████████████████████████████████████| 655/655 [00:09<00:00, 66.26it/s]
Test_hours= 1.1517442554799706
No Data Augmentation.
----------
Preparing metadata...
Including:
LJSpeech

  0%|                                                              | 0/1 [00:00<?, ?it/s]Singer LJSpeech_LJSpeech: 1366.18 mins for training
----------

100%|██████████████████████████████████████████████████████| 1/1 [00:00<00:00,  4.25it/s]
Extracting acoustic features for LJSpeech using 8 workers ...
types:  ['train', 'test']
100%|██████████████████████████████████████████████| 13100/13100 [02:56<00:00, 74.35it/s]
Extracting content features for LJSpeech...
Extracting phoneme sequence for LJSpeech...
  2%|▉                                             | 255/13100 [03:18<2:50:16,  1.26it/s]

```

**Comment by treya-lin** [comment]
@RMSnow @lmxue 
Hi, I think I figured out why the phoneme extraction was very slow. It is not related to the IO speed but because of the repetition of creating G2p class in the code.

The creation of G2p was written inside `def preprocess_english`, which means every time it phonemize a piece of text, it needs to recreate this object.

[g2p_module.py](https://github.com/open-mmlab/Amphion/blob/befdee85e4ea11d659ef070730c40fac31aa9097/text/g2p_module.py#L205C1-L218C43)
```
from g2p_en import G2p
...
    def preprocess_english(self, text):
        text = text.rstrip(punctuation)


        g2p = G2p()
        phones = []
        words = re.split(r"([,;.\-\?\!\s+])", text)
        for w in words:
            if w.lower() in self.lexicon:
                phones += self.lexicon[w.lower()]
            else:
                phones += list(filter(lambda p: p != " ", g2p(w)))
        phones = "}{".join(phones)
        phones = re.sub(r"\{[^\w\s]?\}", "{sp}", phones)
        phones = phones.replace("}{", " ")
```

The creation of G2p class is very slow as shown below, each operation takes 0.5-1.5s. So for 13k lines it will no doubt take ages. Why would it be very fast at @lmxue 's end? Is the repo in your local environment different from current one?

```
from g2p_en import G2p
import time

for i in range(10):
  start = time.time()
  g2p = G2p()
  print(time.time() - start)

1.5413975715637207
0.44445133209228516
1.1414928436279297
0.4576385021209717
1.0855536460876465
1.1499791145324707
0.4570882320404053
1.1194915771484375
1.19093656539917
0.4555625915527344
```

After I tried moving this line outside the function, it took less than one minute to finish this step. Below is how I tested the speed in my notebook. 

```
import os
os.environ['WORK_DIR'] = '.'
import json
from pathlib import Path
from tqdm import tqdm
import time
import re
from string import punctuation

from g2p_en import G2p

from utils.util import load_config
from processors import acoustic_extractor, content_extractor, data_augment, phone_extractor
from text.g2p_module import G2PModule, LexiconModule

g2p = G2p()
def preprocess_english(text):
    text = text.rstrip(punctuation)
    
    phones = []
    words = re.split(r"([,;.\-\?\!\s+])", text)
    for w in words:
        if w.lower() in g2p_module.lexicon:
            phones += g2p_module.lexicon[w.lower()]
        else:
            phones += list(filter(lambda p: p != " ", g2p(w)))
    phones = "}{".join(phones)
    phones = re.sub(r"\{[^\w\s]?\}", "{sp}", phones)
    phones = phones.replace("}{", " ")
    return phones
  
cfg = load_config(Path('egs/tts/VITS/exp_config.json'))
metadata = []
for dataset_type in ['train','test']:
    dataset_output = os.path.join('data_tmp/','LJSpeech' )
    dataset_file = os.path.join(dataset_output, "{}.json".format(dataset_type))
    with open(dataset_file, "r") as f:
        metadata.extend(json.load(f))
        
g2p_module = LexiconModule(cfg.preprocess.lexicon_path)

out_path = 'data_tmp/LJSpeech/phones/'
for utt in tqdm(metadata):
    uid = utt["Uid"]
    text = utt["Text"]
    phone_seq = preprocess_english(text)

    phone_path = os.path.join(out_path, uid + ".phone")
    with open(phone_path, "w") as fin:
        fin.write(" ".join(phone_seq))

100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 13100/13100 [00:53<00:00, 246.95it/s]

```

**Comment by RMSnow** [comment]
@treya-lin Wow, thanks for your advice! Your design is indeed effective. @lmxue Liumeng, would you mind borrowing this design to improve the existing g2p module?

**Comment by lmxue** [comment]
> @treya-lin Wow, thanks for your advice! Your design is indeed effective. @lmxue Liumeng, would you mind borrowing this design to improve the existing g2p module?

Sure. Thanks for the great feedback from @treya-lin. Also, @treya-lin you are welcome to PR to contribute your great idea to the open-source community.

**Comment by lmxue** [comment]
> > It may depend on the io speed of your machine. I tested it on my machine. And it took several minutes to extract phoneme features of all 12,445 utterances in LJSpeech.
> 
> Could you share the whole console output of your preprocessing precedure? I tried cleaning my cache and disk but it is still the same. Here is my console output:
> 
> ```
> $ bash egs/tts/VITS/run.sh
>  --stage 1
> Exprimental Configuration File: /newdisk2T/tts_space/Amphion/egs/tts/VITS/exp_config.json
> Preprocess LJSpeech...
> ----------
> Dataset splits for LJSpeech...
> 
> 13100it [00:00, 432337.83it/s]
> 100%|██████████████████████████████████████████████| 12445/12445 [03:19<00:00, 62.37it/s]
> Train_hours= 22.76966582262538
> 100%|██████████████████████████████████████████████████| 655/655 [00:09<00:00, 66.26it/s]
> Test_hours= 1.1517442554799706
> No Data Augmentation.
> ----------
> Preparing metadata...
> Including:
> LJSpeech
> 
>   0%|                                                              | 0/1 [00:00<?, ?it/s]Singer LJSpeech_LJSpeech: 1366.18 mins for training
> ----------
> 
> 100%|██████████████████████████████████████████████████████| 1/1 [00:00<00:00,  4.25it/s]
> Extracting acoustic features for LJSpeech using 8 workers ...
> types:  ['train', 'test']
> 100%|██████████████████████████████████████████████| 13100/13100 [02:56<00:00, 74.35it/s]
> Extracting content features for LJSpeech...
> Extracting phoneme sequence for LJSpeech...
>   2%|▉                                             | 255/13100 [03:18<2:50:16,  1.26it/s]
> ```

Hi, I checked it and found that the setting of "phone_extractor": "espeak” was used on my testing,  but you used the setting of "phone_extractor": "lexicon".  That's why our two processing time were different.

**Comment by treya-lin** [comment]
> > @treya-lin Wow, thanks for your advice! Your design is indeed effective. @lmxue Liumeng, would you mind borrowing this design to improve the existing g2p module?
> 
> Sure. Thanks for the great feedback from @treya-lin. Besides, @treya-lin you are welcome to PR to contribute your great idea to the open-source community.

Hi sure. I have made the pr https://github.com/open-mmlab/Amphion/pull/30#issue-2041050400, hope it looks good.

**Comment by RMSnow** [comment]
@treya-lin Thanks for your contribution! The PR #30 has been merged.
