### ISSUE TITLE
WhisperX citation for Emilia

### ISSUE THREAD

**Issue by m-bain** [open-mmlab/Amphion#241]
Hi,

Im glad whisperx was helpful for your work, the dataset is a valuable contribution.  Consider citing WhisperX in your paper because the pipeline uses WhisperX thank you.

Max

**Comment by HarryHe11** [comment]
Hi Max @m-bain, Thank you so much for reaching out! As mentioned on our repo, we greatly appreciate the significant contribution of WhisperX. I recently discovered that we forgot to cite WhisperX by mistake. We will update our arXiv submission next week to include the proper citation. Sorry for the inconvenience!
