### ISSUE TITLE
[BUG]: Try to reproduce emilia+amphion, unable to find emilia_dataset dataloader script

### ISSUE THREAD

**Issue by wjddd** [open-mmlab/Amphion#244]
I'm trying to reproduce emilia+amphion in https://mp.weixin.qq.com/s/NDhBe-INw5oTew3ruQ6YSQ and I found this line in valle_ar_trainer.py:
https://github.com/open-mmlab/Amphion/blob/72112a678d90873d8312e8cffd2491ffcdd6b40e/models/tts/valle_v2/valle_ar_trainer.py#L208
But no such file (emilia_dataset.py) in models/tts/valle_v2, only libritts_dataset.py.
Could you provide some detailed instruction on how to reproduce emilia+amphion?

**Comment by jiaqili3** [comment]
Hi @wjddd, For the 'Emilia + Amphion' model you mentioned, the result is not produced by the exact model you mentioned. The valle_v2 model we previously released was an English model and it doesn't support Emilia, because it's released before the dataset. The 'Amphion+Emilia' model release would be a future plan. Thanks!

**Comment by wjddd** [comment]
> Hi @wjddd, For the 'Emilia + Amphion' model you mentioned, the result is not produced by the exact model you mentioned. The valle_v2 model we previously released was an English model and it doesn't support Emilia, because it's released before the dataset. The 'Amphion+Emilia' model release would be a future plan. Thanks!

Thank you so much! BTW, does it mean the 'Amphion+Emilia' model is a brand new model apart from VALLE/NS2/NS3/FS2/VITS/Jets?

**Comment by jiaqili3** [comment]
> > Hi @wjddd, For the 'Emilia + Amphion' model you mentioned, the result is not produced by the exact model you mentioned. The valle_v2 model we previously released was an English model and it doesn't support Emilia, because it's released before the dataset. The 'Amphion+Emilia' model release would be a future plan. Thanks!
> 
> @jiaqili3 Thank you so much! BTW, does it mean the 'Amphion+Emilia' model is a brand new model apart from VALLE/NS2/NS3/FS2/VITS/Jets?

Hi @wjddd, though I didn't work on training the new 'amphion+emilia' model, what I know is that the model architecture integrates most recent advances in TTS, there are papers like seedtts, e3tts, soundstorm, etc. Thanks!
