### ISSUE TITLE
[Help]: onnxruntime.capi.onnxruntime_pybind11_state.InvalidProtobuf: [ONNXRuntimeError] : 7 : INVALID_PROTOBUF : Load model from /data/model_amphion/sig_bak_ovr.onnx failed:Protobuf parsing failed.

### ISSUE THREAD

**Issue by WhXmURandom** [open-mmlab/Amphion#248]
## Problem Overview
I ran the AudioPipeline with CPU，but this error happened.

## Steps Taken
(Detail your attempts to resolve the issue, including any relevant steps or processes.)
1. Config/File changes: ...
2. Run command: ...
3. See errors: ...

## Expected Outcome
(A clear and concise description of what you expected to happen.)

## Screenshots
(If applicable, add screenshots to help explain your problem.)
<img width="1072" alt="onnx" src="https://github.com/user-attachments/assets/da3c3cb3-a174-4710-a50a-8e88c3ed4025">

## Environment Information
 - Operating System: [e.g. Ubuntu 20.04.5 LTS]
 - Python Version: [e.g. Python 3.9.15]
 - Driver & CUDA Version: [e.g. Driver 470.103.01 & CUDA 11.4]
 - Error Messages and Logs: [If applicable, provide any error messages or relevant log outputs]

## Additional context
(Add any other context about the problem here.)

**Comment by alexvioni** [comment]
Hi! I face the same error, could you please elaborate on how you solved it?
Thanks a lot

**Comment by WhXmURandom** [comment]
Don't use wget， just download manually.

**Comment by alexvioni** [comment]
I also did that some time ago after I posted the question, and it worked! Thanks a lot
Useful to be here for others who might be wondering as well.
