### ISSUE TITLE
[Feature]: Flow-based Model

### ISSUE THREAD

**Issue by Ming-er** [open-mmlab/Amphion#250]
Hi, recent days have witnessed a lot of flow-based models achieving sota tts and tta performance. I wonder if there are any plans to release some codes for flow-based models, such as voicebox. Thanks.

**Comment by jiaqili3** [comment]
Hi @Ming-er , yes we do have plans to train flow matching models for TTS, and we'll definitely release them if they perform good. We welcome any advice on which models to reproduce. Thanks!
