### ISSUE TITLE
Avoiding hard coding in dataset file

### ISSUE THREAD

**Issue by nghiahuynh-ai** [open-mmlab/Amphion#254]
![Untitled](https://github.com/user-attachments/assets/d916d714-9696-4a0d-8b6e-554454e19069)

**Comment by jiaqili3** [comment]
@nghiahuynh-ai Thanks for the advice, it's surely a good practice to avoid hard coding configurations. In this specific case, limiting the duration of training samples there for libritts is understandable, and there's a printout for this. I'll add a pr to improve this.
