### ISSUE TITLE
FaCodec pretrained model dataset info

### ISSUE THREAD

**Issue by acul3** [open-mmlab/Amphion#257]
thank you for releasing facodec 

really look forward to train or finetune

can you provide information , dataset (50k hours and 1 million speakers) to train facodec ? and maybe information of language also 

thanks you.

@Plachtaa

**Comment by Plachtaa** [comment]
Hi there, thanks for your interest.
The dataset used for training was Emilia-50k. Please refer to [this page](https://github.com/open-mmlab/Amphion/tree/main/preprocessors/Emilia) about usage.

**Comment by acul3** [comment]
thanks you for the answer

**Comment by ZhengRachel** [comment]
> Hi there, thanks for your interest. The dataset used for training was Emilia-50k. Please refer to [this page](https://github.com/open-mmlab/Amphion/tree/main/preprocessors/Emilia) about usage.

Hi @Plachtaa ! Since I can't find any concrete information about Emilia-50k on the page you refer to, may I ask does Emilia-50k correspond to the English part or Chinese part of the current Emilia-101k? Or is it also a multi-lingual speech corpus?
