### ISSUE TITLE
[Help]: Installation failed using setup installer

### ISSUE THREAD

**Issue by GryffindorLi** [open-mmlab/Amphion#284]
## Problem Overview
I tried to install `Amphion` following the setup installer instructions, but I failed at the `fairseq` installation step.
![image](https://github.com/user-attachments/assets/d71b4ce4-3a58-49eb-8a24-02fd035deb17)

I also tried to use a newer version of python (3.11) and remove the version specification in the `env.sh` but got the same outcome.

## Steps Taken
1. Install follow the seup installer instructions, but failed.
2. Install with Python 3.11, failed.
3. Install without version specification, failed.

## Expected Outcome
I want to install `Amphion` in a Conda environment successfully.

## Environment Information
 - Operating System: Ubuntu 22.04 LTS]
 - Python Version: Python 3.9.15 & Python 3.11
 - Driver & CUDA Version: Driver Version: 560.35.03      CUDA Version: 12.6
 - Error Messages and Logs: See screenshot above.

**Comment by cpken** [comment]
我也一样安装不成功（Python 3.9.20）

**Comment by cpken** [comment]
把 pip 的版本降低到 24.0 可以安装成功
```shell
$ pip install pip==24.0
$ pip install fairseq
```
