### ISSUE TITLE
Will the maskgct training code be made public?

### ISSUE THREAD

**Issue by splinter21** [open-mmlab/Amphion#289]
RT

**Comment by fakerybakery** [comment]
Hi,
Thanks for releasing MaskGCT! I was also wondering if the MaskGCT training code would be released.
Thanks!

**Comment by alayamanas** [comment]
Mark, looking forward to it

**Comment by dubeno** [comment]
hi i want to konw, what kind of hardware can run this model, another, the inference speed seem too slow on their website , is there any solution。

**Comment by pashanitw** [comment]
Yes I am looking forward to it ! Training code will definitely make this repo reach more audience

**Comment by HeCheng0625** [comment]
Hello, we are currently developing the next generation of MaskGCT, which is a foundational model supporting various speech generation tasks, including TTS. We plan to open-source fine-tuning (ft) code in this version to adapt to various fine-tuning tasks.

**Comment by fakerybakery** [comment]
> Hello, we are currently developing the next generation of MaskGCT, which is a foundational model supporting various speech generation tasks, including TTS. We plan to open-source fine-tuning (ft) code in this version to adapt to various fine-tuning tasks.

Thanks! Are there any plans to release the pre-training script?

**Comment by MithrilMan** [comment]
any news?
