### ISSUE TITLE
maskgct training code

### ISSUE THREAD

**Issue by mush42** [open-mmlab/Amphion#292]
Hello

How to access training code for [maskgct](https://github.com/open-mmlab/Amphion/tree/main/models/tts/maskgct)

Best
Musharraf

**Comment by mush42** [comment]
Related: #289 289

**Comment by HeCheng0625** [comment]
Hello, we are currently developing the next generation of MaskGCT, which is a foundational model supporting various speech generation tasks, including TTS. We plan to open-source fine-tuning  code in this version to adapt to various fine-tuning tasks.

**Comment by zzchust** [comment]
@HeCheng0625 Maskgct is a great work！ When will the training code be released? Is there a specific plan? This will affect whether the recent project will follow maskgct. If you have a more detailed plan, please explain it.
