### ISSUE TITLE
[Help]: MaskGCT Espeakng Error

### ISSUE THREAD

**Issue by BlockyBard** [open-mmlab/Amphion#298]
I'm trying to run this on windows but I get this error.   File "E:\.conda\envs\voice\Lib\site-packages\phonemizer\backend\espeak\espeak.py", line 49, in __init__
    self._espeak.set_voice(language)
  File "E:\.conda\envs\voice\Lib\site-packages\phonemizer\backend\espeak\wrapper.py", line 249, in set_voice
    raise RuntimeError(  # pragma: nocover
RuntimeError: failed to load voice "ja"

**Comment by yuantuo666** [comment]
Hi, the MaskGCT is built in a Linux environment. For a better coding experience, it is recommended that Linux be used to reproduce.
Besides, we prefer English issues in this repository.
According to the stack trace, it seems to be the problem with the `phonemizer` package, reading their [docs](https://bootphon.github.io/phonemizer/install.html) might be helpful.
