### ISSUE TITLE
Where is the code for VALLE training and inference?

### ISSUE THREAD

**Issue by zzw922cn** [open-mmlab/Amphion#3]
Thanks for your work, much helpful!

**Comment by lmxue** [comment]
> Thanks for your work, much helpful!

Thanks for your attention. The code for VALLE training and inference is coming soon.

**Comment by zhizhengwu** [comment]
> Thanks for your work, much helpful!

#4 Vall-E implementation is in. Feel free to open an issue if there is any bug.

**Comment by JJun-Guo** [comment]
> VALLE

请问VALLE支持中文训练吗？
