### ISSUE TITLE
An issue with the preprocessing part of LibriTTS.

### ISSUE THREAD

**Issue by walker-hyf** [open-mmlab/Amphion#31]
Hello!🤗 When I'm working with the LibriTTS dataset, I noticed that the generated test.json and train.json files do not include the corresponding text for each audio sample. This absence of text information causes an error when trying to extract the phonemes later on. Additionally, I couldn't find any code related to text processing in the preprocessors/libritts.py file.

![image](https://github.com/open-mmlab/Amphion/assets/39916348/e3f0c979-8e37-4d32-88e9-9952bf5cbf11)

![image](https://github.com/open-mmlab/Amphion/assets/39916348/4d05dc96-226f-4d69-add7-82a7da4aee59)

Thanks for the team's hard work and contributions!🎉

**Comment by lmxue** [comment]
Thanks for your feedback. We have updated the  LibriTTS dataset processor https://github.com/open-mmlab/Amphion/pull/25 , where this bug is fixed. So please pull the latest code and try it again.

**Comment by liuyuhualilith** [comment]
Is it better to run the command "sh egs/tts/VALLE/run.sh --stage 1" to retrieve the latest code and try again, and how to just run "Extracting phoneme sequence for libritts..." in the above case? for libritts..." How to run only the "Extracting phoneme sequence for libritts..." part?
Extracting acoustic features for libritts using 4 workers ...
  1% | Casinos | 1704/282359 [04:00<10:55:11, 7.14it/s]
It's too slow.

**Comment by liuyuhualilith** [comment]
> Thanks for your feedback. We have updated the LibriTTS dataset processor in this PR #25 , where this bug is fixed. So please pull the latest code and try it again.

Is it better to run the command "sh egs/tts/VALLE/run.sh --stage 1" to retrieve the latest code and try again, and how to just run "Extracting phoneme sequence for libritts..." in the above case? for libritts..." How to run only the "Extracting phoneme sequence for libritts..." part?
Extracting acoustic features for libritts using 4 workers ...
1% | Casinos | 1704/282359 [04:00<10:55:11, 7.14it/s]
It's too slow.

**Comment by lmxue** [comment]
Thanks for your feedback.

If you only want to extract phoneme sequences, you can comment out lines 105-219 in the file located at https://github.com/open-mmlab/Amphion/blob/b17eea80db16c7e566a7acb426e69ed8f25d3e8e/bins/tts/preprocess.py#L94. This will skip the previous processing steps and extract only the phoneme sequences.

Your feedback inspires us to split the multi-step data processing into individual sub-stages, so that we can flexiblely control over the specific sub-stage of data processing.

Additionally, parallel extraction of acoustic features is currently being tested.

**Comment by liuyuhualilith** [comment]
> Thanks for your feedback.
> 
> If you only want to extract phoneme sequences, you can comment out lines 105-219 in the file located at https://github.com/open-mmlab/Amphion/blob/main/bins/tts/preprocess.py. This will skip the previous processing steps and extract only the phoneme sequences.
> 
> Your feedback inspires us to split the multi-step data processing into individual sub-stages, so that we can flexiblely control over the specific sub-stage of data processing.
> 
> Additionally, parallel extraction of acoustic features is currently being tested.

Thank you for your reply, but I encountered this problem after installing the comment you mentioned, and I can't tell what's causing it.
![image](https://github.com/open-mmlab/Amphion/assets/142777788/177aa7f1-c343-481e-bab5-aa8a50a3f8d3)

**Comment by lmxue** [comment]
The `dataset_types` variable is defined in lines 140-146, so you should keep them uncommented.

**Comment by liuyuhualilith** [comment]
It feels like Amphion has been in a constant process of revision, which is really confusing for a beginner like me. I've been constantly using "git pull origin" to update my local files, but I'm still having the same problem as before.
![image](https://github.com/open-mmlab/Amphion/assets/142777788/f8bea16e-5b49-4935-846e-9007b781f005)

**Comment by baipeng1** [comment]
hi,when i use LibriTTS dataset to train valle,i get this error.
![微信截图_20231220160210](https://github.com/open-mmlab/Amphion/assets/148200188/370c403a-4896-414c-a174-ab38ddef12b5)
i also want to know what should i do to debug this project in PyCharm. i know you use accelerate framework. when start training the project, must use"accelerate launch xxx.py",but i can not configure accelerate launch in my PyCharm.
Thank you!

**Comment by lmxue** [comment]
Please check `egs/tts/VALLE/exp_config.json` in this PR https://github.com/open-mmlab/Amphion/pull/52/files#

**Comment by baipeng1** [comment]
> Please check `egs/tts/VALLE/exp_config.json` in this PR https://github.com/open-mmlab/Amphion/pull/52/files#

thank you!
when i train VALLE

**Comment by baipeng1** [comment]
> Please check `egs/tts/VALLE/exp_config.json` in this PR https://github.com/open-mmlab/Amphion/pull/52/files#

Thank you. When i train VALLE.  i successfullly trained the AR model. But when i trained the NAR model by "sh egs/tts/VALLE/run.sh --stage 2 --model_train_stage 2 --ar_model_ckpt_dir [ARModelPath] --name [YourExptName]
", i met this error.
i can not find the model named pytorch_model.bin, what should i do? Thank you!

**Comment by baipeng1** [comment]
> Please check `egs/tts/VALLE/exp_config.json` in this PR https://github.com/open-mmlab/Amphion/pull/52/files#

Thank you. When i train VALLE. i successfullly trained the AR model. But when i trained the NAR model by "sh egs/tts/VALLE/run.sh --stage 2 --model_train_stage 2 --ar_model_ckpt_dir [ARModelPath] --name [YourExptName]
", i met this error.
![微信图片_20231222172252](https://github.com/open-mmlab/Amphion/assets/148200188/d53cc8be-3f4a-4551-b887-991bc8bf8817)
i can not find the model named pytorch_model.bin, what should i do? Thank you!

**Comment by xinkez** [comment]
@baipeng1 I also met the problem of "can not find the model named pytorch_model.bin", have you solved it?

**Comment by zhizhengwu** [comment]
@HeCheng0625 @lmxue please help with this issue.

**Comment by HeCheng0625** [comment]
If the model is saved as model.safetensors (which means it is not pytorch_model.bin), please use "pip install accelerate==0.24.1"

**Comment by baipeng1** [comment]
> If the model is saved as model.safetensors (which means it is not pytorch_model.bin), please use "pip install accelerate==0.24.1"

Ok, Thank you!

**Comment by baipeng1** [comment]
1、i found that the audio generated by VALLE is poor. I use the train-clean-100.tar.gz dataset to train, Is it because I don't have enough data?

**Comment by lmxue** [comment]
> It feels like Amphion has been in a constant process of revision, which is really confusing for a beginner like me. I've been constantly using "git pull origin" to update my local files, but I'm still having the same problem as before. ![image](https://private-user-images.githubusercontent.com/142777788/291459714-f8bea16e-5b49-4935-846e-9007b781f005.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDM4NTc1MDQsIm5iZiI6MTcwMzg1NzIwNCwicGF0aCI6Ii8xNDI3Nzc3ODgvMjkxNDU5NzE0LWY4YmVhMTZlLTViNDktNDkzNS04NDZlLTkwMDdiNzgxZjAwNS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjMxMjI5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIyOVQxMzQwMDRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01YmMwYTc1ZmIxNmE2MWQ3ZjE1NWE3MGQ3YmUwZGE3MjIzZjQ5Mjc3NTU2NDA5Y2I2NjZjYTQ1YTg4ZjY5YWI0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.j7Dxsdzj084ncTrBABzShwN-CcCBP-hyuWBueEH00Ek)


You can check out whether the generated `.json` file has the `Text` attribute.

**Comment by HarryHe11** [comment]
> 1、i found that the audio generated by VALLE is very poor. it will has this warning "WARNING | phonemizer | words count mismatch on 200.0% of the lines". Is it because of this issue? In addition, i use the train-clean-100.tar.gz dataset to train, Is it because I don't have enough data? 2、We train the AR model to predict the first codebook token,2-7 are NAR model. but i found that VALLE only use NAR model during inference, Is this correct?

@lmxue Could you help with this issue please?

**Comment by lmxue** [comment]
> 1、i found that the audio generated by VALLE is very poor. it will has this warning "WARNING | phonemizer | words count mismatch on 200.0% of the lines". Is it because of this issue? In addition, i use the train-clean-100.tar.gz dataset to train, Is it because I don't have enough data? 2、We train the AR model to predict the first codebook token,2-7 are NAR model. but i found that VALLE only use NAR model during inference, Is this correct?

1. The warning itself is not the cause of the poor performance. In fact, to achieve satisfactory results with VALL-E, it is necessary to train it on a large-scale dataset. As mentioned in the [original paper](https://arxiv.org/pdf/2301.02111.pdf), a training dataset of 60k hours was used to train VALL-E.

2. The NAR model in the second training stage builds upon the AR model trained in the first stage, as outlined in the [VALL-E recipe](https://github.com/open-mmlab/Amphion/blob/843aaef585d52a5b6668efec6000f22e5ddfd148/egs/tts/VALLE/README.md#run-1). Consequently, the NAR model inherits the parameters from the AR model, enabling it to predict the first-layer token using the AR model during inference.

**Comment by HarryHe11** [comment]
Hi @walker-hyf, if you have any more questions regarding the preprocessing part of LibriTTS and Vall-E training, please don't hesitate to reopen this issue!
