### ISSUE TITLE
[Help]: MaskGCT emotion prompt

### ISSUE THREAD

**Issue by skyboooox** [open-mmlab/Amphion#310]
How can i add emotion to generated?
Support any symbols? like [SSML](https://learn.microsoft.com/en-us/azure/ai-services/speech-service/speech-synthesis-markup)

**Comment by yuantuo666** [comment]
Hi, currently, MaskGCT does not support SSML-like prompts. Instead, MaskGCT tries to learn from the reference prompt you provided when inference: 

> MaskGCT can learn the prosody, style, and emotion of prompt speech.
> From: https://maskgct.github.io/#emotion-samples

**Comment by skyboooox** [comment]
thx :D
