### ISSUE TITLE
[Help]: Gradio demo isn't working correctly on either Windows or Ubuntu. I'm experiencing the same issue on both operating systems.

### ISSUE THREAD

**Issue by zelenooki87** [open-mmlab/Amphion#327]
I set up the conda environment according to the instructions, but when I upload any English audio file and type in any English text, I get strange output files. They don't sound anything like your test examples or the few YouTube videos I've seen. I also can't get the demo on Hugging Face Spaces to fully launch so I can troubleshoot the problem.
I've attached screenshots and the input/output files. It's really incoherent, isn't it?
<img width="1280" alt="SNAG-0001" src="https://github.com/user-attachments/assets/4881d72a-a6ae-4691-ba1f-7f8e00685e3b">
[input-2mpvoice.zip](https://github.com/user-attachments/files/17607735/input-2mpvoice.zip)
[output_100timestep.zip](https://github.com/user-attachments/files/17607736/output_100timestep.zip)

**Comment by Tybost** [comment]
This might be due to generating too much dialogue. You can only generate around a sentence right now but long-form is planned: https://github.com/open-mmlab/Amphion/issues/290

**Comment by zelenooki87** [comment]
Strange thing, but with this repo:
https://github.com/justinjohn0306/MaskGCT-Windows
everything working super great.
