### ISSUE TITLE
[Help]: 情绪控制是怎么做的？没有找到示例代码

### ISSUE THREAD

**Issue by smalldaidai** [open-mmlab/Amphion#329]
如题，我在demo页里看到有相当好的情绪控制表现，并且也提到zero-shot也支持情绪控制，但是在示例代码在没有找到，有没有老佬知道的麻烦知会一声，多谢

**Comment by yuantuo666** [comment]
Duplicate with: https://github.com/open-mmlab/Amphion/issues/310
