### ISSUE TITLE
[Help]: How to enable indonesia language output for maskgct ?

### ISSUE THREAD

**Issue by wenhaokho** [open-mmlab/Amphion#331]
## Problem Overview
How to enable indonesia language output for maskgct ?

**Comment by yuantuo666** [comment]
Hi, it requires training or fine-tuning the MaskGCT model to support the new language.

Duplicated with: https://github.com/open-mmlab/Amphion/issues/337, https://github.com/open-mmlab/Amphion/issues/289, and https://github.com/open-mmlab/Amphion/issues/292
