### ISSUE TITLE
[Help]: Pipeline training TTS MaskGCT in new language

### ISSUE THREAD

**Issue by haubui17062019** [open-mmlab/Amphion#337]
I want finetune model TTS MaskGCT in new language, I don't see any tutorial source code, so I don't know what preprocessing is there for data. pls please provide the source code. Thanks!

**Comment by yuantuo666** [comment]
Duplicated with: https://github.com/open-mmlab/Amphion/issues/289 and https://github.com/open-mmlab/Amphion/issues/292
