### ISSUE TITLE
[Help]: How do I use the fast MaskGCT model?

### ISSUE THREAD

**Issue by GUUser91** [open-mmlab/Amphion#362]
I see a dev has uploaded a fast MaskGCT model. How do I use it?
https://huggingface.co/Hecheng0625/fast_maskgct

**Comment by jiaqili3** [comment]
We are actively developing it together with more fast tts models, thanks for the attention and we'll release them soon before new year

**Comment by GalenMarek14** [comment]
> We are actively developing it together with more fast tts models, thanks for the attention and we'll release them soon before new year

Thank you for your work. There is a 'fast_soundstorm' folder in HF, will this be your implementation of Google's SoundStorm? It's another TTS model, right?
Will the new Fast MaskGCT version have the same VRAM requirements or will it be more optimized?
Lastly, is there any change in the release date? If so, any new ETA?
Sorry for the bother and thank you again.

**Comment by jiaqili3** [comment]
> > We are actively developing it together with more fast tts models, thanks for the attention and we'll release them soon before new year
> 
> Thank you for your work. There is a 'fast_soundstorm' folder in HF, will this be your implementation of Google's SoundStorm? It's another TTS model, right? Will the new Fast MaskGCT version have the same VRAM requirements or will it be more optimized? Lastly, is there any change in the release date? If so, any new ETA? Sorry for the bother and thank you again.

Thanks for asking!
You can already find the soundstorm NAR module in current MaskGCT codes. 
VRAM requirements will be reduced
For the ETA, we try our best to do a major release in January, this means a slight delay but more codes, checkpoints, and experiment results are coming.

**Comment by jiaqili3** [comment]
> > > We are actively developing it together with more fast tts models, thanks for the attention and we'll release them soon before new year
> > 
> > 
> > Thank you for your work. There is a 'fast_soundstorm' folder in HF, will this be your implementation of Google's SoundStorm? It's another TTS model, right? Will the new Fast MaskGCT version have the same VRAM requirements or will it be more optimized? Lastly, is there any change in the release date? If so, any new ETA? Sorry for the bother and thank you again.
> 
> Thanks for asking! You can already find the soundstorm NAR module in current MaskGCT codes. VRAM requirements will be reduced For the ETA, we try our best to do a major release in January, this means a slight delay but more codes, checkpoints, and experiment results are coming.

Thank you for your interest for the fast models, and I'm sorry that the codes have not been released, although they're ready for a long time... The reason is that we use a model that is submitted to a conference that has an anonymity period from January to April, during which we cannot post anything about the work🙈 If you're still interested, we'll consider if we could still open source anonymously, thanks!

**Comment by Hyeokiki** [comment]
평가는 speaker similarity, intelligibility (cer, wer, ser), naturalness (utmos, nisqa)
