### ISSUE TITLE
Amount of data to train NaturalSpeech 2

### ISSUE THREAD

**Issue by dongngm** [open-mmlab/Amphion#40]
Hi, may I ask how many hours of audio in the training data to produce the checkpoint used in https://huggingface.co/spaces/amphion/NaturalSpeech2?

Thank you.

**Comment by HeCheng0625** [comment]
We use libritts (about 580 hours, which is much smaller than the origin paper's 5.5w hours) and the latent representation of 24KHz Encodec to train the model, we plan to use more data (> 1w hours) to train NS2 in the future.
