### ISSUE TITLE
how to retrain model ? 

### ISSUE THREAD

**Issue by datnt153** [open-mmlab/Amphion#47]
I have trained a VITS model, but whenever I run the training process again, it starts from epoch 0 instead of continuing from the last epoch. Do you have any solutions for this issue?

**Comment by lmxue** [comment]
Thanks for your feedback. There is a argument `resume` [here](https://github.com/open-mmlab/Amphion/blob/4542a2d7c1e071e5d10b2d3c285bd1383d0f2292/bins/tts/train.py#L57) that can continue training from the last epoch. We'll update the VITS receipt asap to make the usage more convenient.
