### ISSUE TITLE
Fine-tune the SVC model for a new singer?

### ISSUE THREAD

**Issue by vahidEtt** [open-mmlab/Amphion#49]
Thanks for the great work. 

I was wondering if is it possible to fine-tune the SVC model for a new singer. if yes, can you refer me to the data format?

**Comment by lmxue** [comment]
@RMSnow

**Comment by RMSnow** [comment]
Thanks for your attention!

Actually the code of fine-tuning a SVC model has been integrated. However, the existing recipe and doc for this part is immature. If it is urgent, you can explore the existing code: 

- The entrance of fine-tuning from an existing checkpoint is [here](https://github.com/open-mmlab/Amphion/blob/4542a2d7c1e071e5d10b2d3c285bd1383d0f2292/egs/svc/_template/run.sh#L94C16-L94C16).
- You can refer to the comments [here](https://github.com/open-mmlab/Amphion/blob/4542a2d7c1e071e5d10b2d3c285bd1383d0f2292/egs/svc/_template/run.sh#L33) and specify that `--resume_type finetune`

I'll refine the recipe and doc to provide the fine-tuning part as a supplement, ASAP. Hope I can finish it in this week :)

**Comment by vahidEtt** [comment]
Great. Thanks for the detailed answers. I think it should be enough to start!

Thanks again for the great work!
