### ISSUE TITLE
The instructions aren't complete, how do you run it?

### ISSUE THREAD

**Issue by AntDX316** [open-mmlab/Amphion#57]
git clone https://github.com/open-mmlab/Amphion.git
cd Amphion

# Install Python Environment
conda create --name amphion python=3.9.15
conda activate amphion

# Install Python Packages Dependencies
sh env.sh

I've done this but what do I do now?

**Comment by RMSnow** [comment]
Which model do you want to train? You've succeeded to install the environment. Next step is to choose a model and go ahead 😄 The supported tasks can be seen [here](https://github.com/open-mmlab/Amphion?tab=readme-ov-file#-usage-in-python).

**Comment by zhizhengwu** [comment]
closing this issue. Feel free to reopen if you can't resolve yourself.
