### ISSUE TITLE
Does it support for multilanguage?

### ISSUE THREAD

**Issue by tosunozgun** [open-mmlab/Amphion#62]
Hi, thanks for your nice work.,

I have a 20k hours turkish dataset, can i train non-english model with this repository.
I see that you used g2p module and its only for english.

Thanks,

**Comment by lmxue** [comment]
We support [espeak](https://github.com/open-mmlab/Amphion/blob/b0923446d6d7cef6b545e69ba7ea6af39e251c86/text/g2p_module.py#L136) to extract IPA (International Phonetic Alphabet), which supports  [100 languages](https://github.com/espeak-ng/espeak-ng/blob/master/docs/languages.md), including Turkish.

**Comment by tosunozgun** [comment]
thanks you.
