### ISSUE TITLE
When I running "sh egs/svc/MultipleContentsSVC/run.sh --stage 1",it does't work! Where can I get '[Opencpop dataset path]/segments/train.txt'

### ISSUE THREAD

**Issue by ErLongHuDaoGe** [open-mmlab/Amphion#70]
Exprimental Configuration File: /home/ayit/Downloads/Amphion/egs/svc/MultipleContentsSVC/exp_config.json
Preprocess m4singer...
----------
Preparing test samples for m4singer...

M4Singer: 20 singers, 20896 utterances (419 unique songs)
Singers: 
Alto-1	Alto-2	Alto-3	Alto-4	Alto-5	Alto-6	Alto-7	Bass-1	Bass-2	Bass-3Soprano-1	Soprano-2	Soprano-3	Tenor-1	Tenor-2	Tenor-3	Tenor-4	Tenor-5	Tenor-6	Tenor-7
  0%|                                                  | 0/20 [00:00<?, ?it/s]/home/ayit/Downloads/Amphion/preprocessors/m4singer.py:106: FutureWarning: get_duration() keyword argument 'filename' has been renamed to 'path' in version 0.10.0.
	This alias will be removed in version 1.0.
  duration = librosa.get_duration(filename=res["Path"])
100%|█████████████████████████████████████████| 20/20 [00:05<00:00,  3.93it/s]
#Train = 20739, #Test = 122
#Train hours= 29.48246345867975, #Test hours= 0.16981873925264554
Preprocess opencpop...
----------
Dataset splits for opencpop...

Traceback (most recent call last):
  File "/home/ayit/Downloads/Amphion/bins/svc/preprocess.py", line 182, in <module>
    main()
  File "/home/ayit/Downloads/Amphion/bins/svc/preprocess.py", line 178, in main
    preprocess(cfg, args)
  File "/home/ayit/Downloads/Amphion/bins/svc/preprocess.py", line 83, in preprocess
    preprocess_dataset(
  File "/home/ayit/Downloads/Amphion/preprocessors/processor.py", line 48, in preprocess_dataset
    opencpop.main(dataset, output_path, dataset_path)
  File "/home/ayit/Downloads/Amphion/preprocessors/opencpop.py", line 66, in main
    res, hours = get_uid2utt(opencpop_path, dataset, dataset_type)
  File "/home/ayit/Downloads/Amphion/preprocessors/opencpop.py", line 26, in get_uid2utt
    lines = get_lines(file)
  File "/home/ayit/Downloads/Amphion/preprocessors/opencpop.py", line 15, in get_lines
    with open(file, "r") as f:
FileNotFoundError: [Errno 2] No such file or directory: '[Opencpop dataset path]/segments/train.txt'

**Comment by ErLongHuDaoGe** [comment]
I can't find '[Opencpop dataset path]/segments/train.txt'

**Comment by RMSnow** [comment]
Hi, have you downloaded the Opencpop dataset? If so, you need to replace the `[Opencpop dataset path]` with the real dataset path. The downloading instruction can be seen [here](https://github.com/open-mmlab/Amphion/blob/main/egs/datasets/README.md#opencpop).

**Comment by RMSnow** [comment]
Hi @ErLongHuDaoGe, if you have any further questions, feel free to re-open this issue!
