### ISSUE TITLE
ImportError: cannot import name 'VariableSampler' from 'models.base.base_sampler'

### ISSUE THREAD

**Issue by Abel1802** [open-mmlab/Amphion#76]
When I run "sh egs/tts/VITS/run.sh --stage 2 --name ljs_base"
I had an issue with the following:

"""
Traceback (most recent call last):
  File "/home/zhangy33/data1/lz/tts/Amphion/bins/tts/train.py", line 13, in <module>
    from models.tts.naturalspeech2.ns2_trainer import NS2Trainer
  File "/home/zhangy33/data1/lz/tts/Amphion/models/tts/naturalspeech2/ns2_trainer.py", line 16, in <module>
    from models.base.base_sampler import VariableSampler
ImportError: cannot import name 'VariableSampler' from 'models.base.base_sampler'
"""

I didn't find the "VariableSampler" when I checked the "models.base.base_sampler.py".

Can you help me with this problem?

**Comment by lmxue** [comment]
@HeCheng0625  Please follow up on this issue, in which `VariableSampler ` used in `ns2_trainer.py` is not imported correctly.

**Comment by HeCheng0625** [comment]
Hi @Abel1802, we have already fixed the bug and merged the code, if you have any further question about it, feel free to reopen this issue.
