### ISSUE TITLE
There is no whisper in the pretrained folder, should I create it myself?

### ISSUE THREAD

**Issue by c469591** [open-mmlab/Amphion#79]
Hello, I just cloned the repository, but there's no whisper in the pretrained folder. Should I create it myself?
Additionally, is the model being used Whisper v3? Can I switch to a larger model myself?
Thank you

**Comment by Adorable-Qin** [comment]
Hi @c469591 !

You don't need to worry about the path unless you want to use your local model. If you do not download the model beforehand, Amphion will take control and automatically download the model you specify.

The default model in our config is `medium`. According to OpenAI's docs, you could use one of the following 
`tiny.en`, `tiny`, `base.en`, `base`, `small.en`, `small`, `medium.en`, `medium`, `large-v1`, `large-v2`, `large-v3`, `large` as your content feature extractor. I think you could use `large-v3` as your extractor if you prefer Whisper v3.

You could modify your config to specify the Whisper model like this:
`"preprocess": {"whisper_model": "large-v3"}`

**Comment by c469591** [comment]
Thank you for your detailed explanation; I understand now.

**Comment by c469591** [comment]
Oh, there's something else I'm puzzled about. I heard that Whisper v3 uses 128 channels while v2 uses 80 channels. Which configuration file needs to be modified for this?
thank

**Comment by Adorable-Qin** [comment]
> Oh, there's something else I'm puzzled about. I heard that Whisper v3 uses 128 channels while v2 uses 80 channels. Which configuration file needs to be modified for this? thank

Thanks for your valuable information!

I noticed that Whisper-v3 requires `n_mels` to be set to `128`, while for other models this value is `80`. We haven't provided a config-modifying method to adapt to Whisper-v3 yet, and we will fix this problem later.

You could simply modify the line 229 in `Amphion/processors/content_extractor.py` by adding an argument `n_mels=128` of `whisper.log_mel_spectrogram()` to support Whisper-v3.

The fixed line would look like this: `batch_mel = whisper.log_mel_spectrogram(wavs, n_mels=128, device=self.model.device)`

**Comment by RMSnow** [comment]
Hi @c469591 , if you have any further questions about whisper extractor, feel free to re-open this issue. We are glad to follow up!

**Comment by Serdcoff** [comment]
> > Oh, there's something else I'm puzzled about. I heard that Whisper v3 uses 128 channels while v2 uses 80 channels. Which configuration file needs to be modified for this? thank
> 
> Thanks for your valuable information!
> 
> I noticed that Whisper-v3 requires `n_mels` to be set to `128`, while for other models this value is `80`. We haven't provided a config-modifying method to adapt to Whisper-v3 yet, and we will fix this problem later.
> 
> You could simply modify the line 229 in `Amphion/processors/content_extractor.py` by adding an argument `n_mels=128` of `whisper.log_mel_spectrogram()` to support Whisper-v3.
> 
> The fixed line would look like this: `batch_mel = whisper.log_mel_spectrogram(wavs, n_mels=128, device=self.model.device)`

Hi there. I have close question about using Emilia-pipe with my own pre-trained whisper-large v3 model, because my language (UZ) not supported from the box in Whisper-large V3. Where I need to change the pass to my pre-trained model Whipser-large V3 if I want to use it with Emilia-Pipe on my local machine?
Thank you.

**Comment by Adorable-Qin** [comment]
> > > Oh, there's something else I'm puzzled about. I heard that Whisper v3 uses 128 channels while v2 uses 80 channels. Which configuration file needs to be modified for this? thank
> > 
> > 
> > Thanks for your valuable information!
> > I noticed that Whisper-v3 requires `n_mels` to be set to `128`, while for other models this value is `80`. We haven't provided a config-modifying method to adapt to Whisper-v3 yet, and we will fix this problem later.
> > You could simply modify the line 229 in `Amphion/processors/content_extractor.py` by adding an argument `n_mels=128` of `whisper.log_mel_spectrogram()` to support Whisper-v3.
> > The fixed line would look like this: `batch_mel = whisper.log_mel_spectrogram(wavs, n_mels=128, device=self.model.device)`
> 
> Hi there. I have close question about using Emilia-pipe with my own pre-trained whisper-large v3 model, because my language (UZ) not supported from the box in Whisper-large V3. Where I need to change the path to my pre-trained model Whipser-large V3 if I want to use it with Emilia-Pipe on my local machine? Thank you.

Hi @Serdcoff ! Thank you for bringing this issue to our attention. 
@yuantuo666 Could you help provide guidance on using the fine-tuned Whisper-v3 in the Emilia-pipeline?

**Comment by yuantuo666** [comment]
> > > Oh, there's something else I'm puzzled about. I heard that Whisper v3 uses 128 channels while v2 uses 80 channels. Which configuration file needs to be modified for this? thank
> > 
> > 
> > Thanks for your valuable information!
> > I noticed that Whisper-v3 requires `n_mels` to be set to `128`, while for other models this value is `80`. We haven't provided a config-modifying method to adapt to Whisper-v3 yet, and we will fix this problem later.
> > You could simply modify the line 229 in `Amphion/processors/content_extractor.py` by adding an argument `n_mels=128` of `whisper.log_mel_spectrogram()` to support Whisper-v3.
> > The fixed line would look like this: `batch_mel = whisper.log_mel_spectrogram(wavs, n_mels=128, device=self.model.device)`
> 
> Hi there. I have close question about using Emilia-pipe with my own pre-trained whisper-large v3 model, because my language (UZ) not supported from the box in Whisper-large V3. Where I need to change the path to my pre-trained model Whipser-large V3 if I want to use it with Emilia-Pipe on my local machine? Thank you.

Hi @Serdcoff, in the Emilia-Pipe, we use faster-whisper as our backend, which means your pre-trained model might not work before conversion. Here are the steps:
1. Follow [this guide](https://github.com/SYSTRAN/faster-whisper?tab=readme-ov-file#model-conversion) to convert your model to quantized format.
2. Upload the quantized model to HuggingFace or save it to your local path. E.g., `username/whisper-large-v3.uz`
3. Then specify the model arch when running the pipeline: `main.py --whisper_arch username/whisper-large-v3.uz`

If you encounter any problems, feel free to create a new issue to report. (Since this issue is closed and not related to Emilia-pipe)
