### ISSUE TITLE
ImportError: cannot import name 'quote' from 'urllib' (/root/miniconda3/lib/pyth on3.8/urllib/__init__.py)

### ISSUE THREAD

**Issue by c469591** [open-mmlab/Amphion#81]
Hello, I encountered an error while using run.sh in vits svc. How can I resolve this?
thanks!

 root@autodl-container-06e841a5b8-eff3dbef:~/Amphion/egs/svc/VitsSVC# ./run.sh --
 stage 1                                                                         
 Exprimental Configuration File: /root/Amphion/egs/svc/VitsSVC/exp_config.json   
 2023-12-31 10:45:06 | INFO | fairseq.tasks.text_to_speech | Please install tenso
 rboardX: pip install tensorboardX                                               
 Traceback (most recent call last):                                              
   File "/root/Amphion/bins/svc/preprocess.py", line 19, in <module>             
     from processors import acoustic_extractor, content_extractor, data_augment  
   File "/root/Amphion/processors/data_augment.py", line 12, in <module>         
     import parselmouth                                                          
   File "/root/miniconda3/lib/python3.8/site-packages/parselmouth/__init__.py", l
 ine 22, in <module>                                                             
     from parselmouth.base import Parselmouth                                    
   File "/root/miniconda3/lib/python3.8/site-packages/parselmouth/base.py", line 
 30, in <module>                                                                 
     from parselmouth.adapters.dfp.interface import DFPInterface                 
   File "/root/miniconda3/lib/python3.8/site-packages/parselmouth/adapters/dfp/in
 terface.py", line 17, in <module>                                               
     from urllib import quote                                                    
 ImportError: cannot import name 'quote' from 'urllib' (/root/miniconda3/lib/pyth
 on3.8/urllib/__init__.py)

**Comment by viewfinder-annn** [comment]
Hi @c469591 thank you for your interest in our work!

It seems that you are encountering a problem related to the dependency package `parselmouth` and I think re-installing this package may help. Please note that you need to run this which is different from this package name itself:

```bash
pip uninstall praat-parselmouth
pip install praat-parselmouth
```

If you still cannot run properly, try remove current environment and create a new one following the Installation section in readme.md.

Here is a similar issue in the parselmouth official repo where they also recommended re-install and use the special package name, fyi: https://github.com/YannickJadoul/Parselmouth/issues/32

Feel free to follow up if you have any other questions, happy new year!

**Comment by c469591** [comment]
Thank you, everything is back to normal after I reconfigured the environment.
