### ISSUE TITLE
During preprocessing, my custom dataset could not be found.

### ISSUE THREAD

**Issue by c469591** [open-mmlab/Amphion#83]
Hello, I've encountered a problem again. It might be a simple mistake, but I can't find a way to solve it.
When running ./run.sh --stage 1, it couldn't find the files in my data set.
I've already checked the read.md, but I still can't resolve this error. I need more guidance, thank you!

My data is placed here →
/root/Amphion/egs/datasets/
My wav file is here →
/root/Amphion/egs/datasets/tingting/tingting/298.wav
The beginning part of my exp_config.json file→
{
    "base_config": "config/vitssvc.json",
    "model_type": "VitsSVC",
    "dataset": [
        "tingting"
    ],
    "dataset_path": {
        // TODO: Fill in your dataset path
        "tingting": "/root/Amphion/egs/datasets/"
    },

The following is the content of the error report→
 (amphion) root@autodl-container-25b911bc3c-59272fc1:~/Amphion/egs/svc/VitsSVC# .
 /run.sh --stage 1                                                               
 Exprimental Configuration File: /root/Amphion/egs/svc/VitsSVC/exp_config.json   
 Preprocess tingting...                                                          
 No Data Augmentation.                                                           
 ----------                                                                      
 Preparing metadata...                                                           
 Including:                                                                      
 tingting                                                                        
   0%|                                                     | 0/1 [00:00<?, ?it/s]
 Traceback (most recent call last):                                              
   File "/root/Amphion/bins/svc/preprocess.py", line 183, in <module>            
     main()                                                                      
   File "/root/Amphion/bins/svc/preprocess.py", line 179, in main                
     preprocess(cfg, args)                                                       
   File "/root/Amphion/bins/svc/preprocess.py", line 108, in preprocess          
     cal_metadata(cfg)                                                           
   File "/root/Amphion/preprocessors/metadata.py", line 27, in cal_metadata      
     assert os.path.exists(save_dir)                                             
 AssertionError

**Comment by viewfinder-annn** [comment]
Hi @c469591 !
You need to specify in your custom dataset name in `use_custom_dataset` field like this:
```json
{
    "base_config": "config/vitssvc.json",
    "model_type": "VitsSVC",
    "dataset": [
        "tingting"
    ],
    "dataset_path": {
        "tingting": "[Your Dataset Path]"
    },
    "use_custom_dataset": ["tingting"],
...
```
You can see the MultipleContentSVC document for more details [here](https://github.com/open-mmlab/Amphion/tree/main/egs/svc/MultipleContentsSVC#custom-dataset).

It's our lag for the VitsSVC document, custom dataset is a developing feature among different tasks and models. Thank you for your consideration and support!

**Comment by c469591** [comment]
Thank you very much, the issue has been resolved.
