### ISSUE TITLE
OSError: Model file not found: pretrained/contentvec/checkpoint_best_legacy_500.  pt                                                                              

### ISSUE THREAD

**Issue by c469591** [open-mmlab/Amphion#87]
Hello, I've encountered another strange issue, again while using vits svc.
I ran the following command →
./run.sh --stage 1
I've already placed the required model files on this path →
"/root/Amphion/pretrained/contentvec/checkpoint_best_legacy_500.pt                                                                              "

Here is the error report →
 Traceback (most recent call last):                                              
   File "/root/Amphion/bins/svc/preprocess.py", line 183, in <module>            
     main()                                                                      
   File "/root/Amphion/bins/svc/preprocess.py", line 179, in main                
     preprocess(cfg, args)                                                       
   File "/root/Amphion/bins/svc/preprocess.py", line 165, in preprocess          
     extract_content_features(dataset, output_path, cfg, args.num_workers)       
   File "/root/Amphion/bins/svc/preprocess.py", line 64, in extract_content_featu
 res                                                                             
     content_extractor.extract_utt_content_features_dataloader(                  
   File "/root/Amphion/processors/content_extractor.py", line 488, in extract_utt
 _content_features_dataloader                                                    
     extractor.load_model()                                                      
   File "/root/Amphion/processors/content_extractor.py", line 247, in load_model 
     models, saved_cfg, task = checkpoint_utils.load_model_ensemble_and_task(    
   File "/root/miniconda3/envs/amphion/lib/python3.9/site-packages/fairseq/checkp
 oint_utils.py", line 423, in load_model_ensemble_and_task                       
     raise IOError("Model file not found: {}".format(filename))                  
 OSError: Model file not found: pretrained/contentvec/checkpoint_best_legacy_500.
 pt

**Comment by c469591** [comment]
Additionally, I have also uploaded the following model files to the server:
/root/Amphion/pretrained/bigvgan/args.json
/root/Amphion/pretrained/bigvgan/400000.pt
/root/Amphion/pretrained/hifigan/hifigan_speech/

**Comment by viewfinder-annn** [comment]
Hi @c469591 ,

That's because all scripts in amphion(including data preprocessing, training, inference, etc.) should be executed under the `Amphion` root path(Or your custom codebase name). Then you can run the scripts properly. See note [here](https://github.com/open-mmlab/Amphion/tree/main/egs/svc/VitsSVC#vits-for-singing-voice-conversion) for more information.

```bash
cd Amphion
sh egs/svc/VitsSVC/run.sh --stage 1
```

If you have any further questions regarding to running scripts properly for VitsSVC, feel free to follow up!

**Comment by c469591** [comment]
I'm running it in the root directory.
 (amphion) root@autodl-container-25b911bc3c-59272fc1:~/Amphion# pwd              
 /root/Amphion                                                                   

Then run
egs/svc/VitsSVC/run.sh --stage 1

But still
 OSError: Model file not found: pretrained/contentvec/checkpoint_best_legacy_500. pt

**Comment by viewfinder-annn** [comment]
It seems that I cannot reproduce your problem. Could you please paste your `preprocess` field in `exp_config.json` as well as the entire output for running `egs/svc/VitsSVC/run.sh --stage 1`?

**Comment by RMSnow** [comment]
> Additionally, I have also uploaded the following model files to the server: /root/Amphion/pretrained/bigvgan/args.json /root/Amphion/pretrained/bigvgan/400000.pt /root/Amphion/pretrained/hifigan/hifigan_speech/

Hi @c469591, did you download the contentvec ckpt file? If so, it seems you will have `/root/Amphion/pretrained/checkpoint_best_legacy_500.pt`.

**Comment by c469591** [comment]
Hello, so isn't the file checkpoint_best_legacy_500.pt placed in the contentvec folder?
Since I've read the instructions here→
https://github.com/open-mmlab/Amphion/blob/main/pretrained/README.md
Inside, it instructed me to place the documents into the contentvec folder.
However, I haven't moved the documents to the pretrained folder for testing yet.

**Comment by c469591** [comment]
Now, I have copied the document over, and this is the current file path./root/Amphion/pretrained/checkpoint_best_legacy_500.pt
And there is also here
"/root/Amphion/pretrained/contentvec/checkpoint_best_legacy_500.pt                                                                              "
But it still reports an error.
 Traceback (most recent call last):                                              
   File "/root/Amphion/bins/svc/preprocess.py", line 183, in <module>            
     main()                                                                      
   File "/root/Amphion/bins/svc/preprocess.py", line 179, in main                
     preprocess(cfg, args)                                                       
   File "/root/Amphion/bins/svc/preprocess.py", line 165, in preprocess          
     extract_content_features(dataset, output_path, cfg, args.num_workers)       
   File "/root/Amphion/bins/svc/preprocess.py", line 64, in extract_content_featu
 res                                                                             
     content_extractor.extract_utt_content_features_dataloader(                  
   File "/root/Amphion/processors/content_extractor.py", line 488, in extract_utt
 _content_features_dataloader                                                    
     extractor.load_model()                                                      
   File "/root/Amphion/processors/content_extractor.py", line 247, in load_model 
     models, saved_cfg, task = checkpoint_utils.load_model_ensemble_and_task(    
   File "/root/miniconda3/envs/amphion/lib/python3.9/site-packages/fairseq/checkp
 oint_utils.py", line 423, in load_model_ensemble_and_task                       
     raise IOError("Model file not found: {}".format(filename))                  
 OSError: Model file not found: pretrained/contentvec/checkpoint_best_legacy_500.
 pt                                                                              
I'm not sure where exactly the problem lies—is there an error in the path within the .py file itself?

**Comment by c469591** [comment]
I'm sorry, I missed a reply. Below is my profile.
[exp_config.json](https://github.com/open-mmlab/Amphion/files/13810418/exp_config.json)

**Comment by RMSnow** [comment]
> I'm sorry, I missed a reply. Below is my profile. [exp_config.json](https://github.com/open-mmlab/Amphion/files/13810418/exp_config.json)

Hi @c469591, it is a little strange. How about you specify the contentvec path as the real absolute path? Here is the original json file (line51 in your `exp_config.json`):

```json
"contentvec_file": "pretrained/contentvec/checkpoint_best_legacy_500.pt"
```

You can change this value to your downloaded contentvec filepath.

**Comment by RMSnow** [comment]
Hi @c469591 , you can also use the simplest test to verify the contentvec filepath is normal or not. In your terminal, activate the python enviroment (by run the command `python`) and then:

```python
import torch
model = torch.load("[Your Downloaded ContentVec Filepath]")
```

**Comment by c469591** [comment]
Hello everyone, I've finally resolved the issue. It turned out that there were some extra spaces at the end of my document Ming Zhong, which might have been created for some unknown reason when I uploaded the model files to the server. Everything returned to normal after deleting those spaces. Thank you all for your patient responses.
