### ISSUE TITLE
[Feature]: could you publish releases on github please ?

### ISSUE THREAD

**Issue by happysalada** [open-mmlab/Amphion#99]
it would make it much easier package this for linux distribution to build from source

**Comment by RMSnow** [comment]
Hi @happysalada, thanks for your constructive advice! We will prepare one in these days, @yuantuo666 and @Lokshaw-Chau will follow up it. Hope we can finish it in next week 😄

**Comment by yuantuo666** [comment]
We are working on building a Docker image and preparing data for a release version. Drafted docker install guide information can be found here: https://github.com/yuantuo666/Amphion/tree/add-docker?tab=readme-ov-file#docker-install

**Comment by happysalada** [comment]
For nixos for example, packages are built , so we wont use docker. As long as the releases are tagged on github, personally im happy !

**Comment by HarryHe11** [comment]
Hi @yuantuo666, @Lokshaw-Chau, could you please provide a concrete timeline for our GitHub releases?

**Comment by happysalada** [comment]
Thank you !
Nixos builds from source not using docker, so im going to have to adapt your env.sh but its okay.
I only need to have release tags on github !
Thank you !

**Comment by yuantuo666** [comment]
Hi @happysalada, the release tags have been available now, feel free to check here: https://github.com/open-mmlab/Amphion/releases

If you have any further questions about releases, feel free to re-open this issue. We are glad to follow up!
